FTX_MAX_REQUESTS_RESET = "FTX_MAX_REQUESTS_RESET"
FTX_TOTAL_REQUESTS = "FTX_TOTAL_REQUESTS"

API_URL = "https://ftx.com/api"
MAX_RESULTS = 200
MIN_ELAPSED_PER_REQUEST = 1 / 30.0  # 30 req/s

# For MOVE
BTC = "BTC"
BTCMOVE = "BTC-MOVE"
