# Generated by Django 5.2.9 on 2025-12-20 03:27
import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models

import quant_tick.models.base
import quant_tick.models.trades


def fake(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "global symbol",
                "verbose_name_plural": "global symbols",
                "db_table": "quant_candles_global_symbol",
            },
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("binance", "Binance"),
                            ("bitfinex", "Bitfinex"),
                            ("bitmex", "BitMEX"),
                            ("bybit", "Bybit"),
                            ("coinbase", "Coinbase"),
                        ],
                        max_length=255,
                        verbose_name="exchange",
                    ),
                ),
                (
                    "api_symbol",
                    models.CharField(max_length=255, verbose_name="API symbol"),
                ),
                (
                    "significant_trade_filter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="If trades are aggregated, they can be further filtered according to the algorithm described in the documentation.",
                        verbose_name="significant trade filter",
                    ),
                ),
                (
                    "global_symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbols",
                        to="quant_tick.globalsymbol",
                    ),
                ),
                (
                    "aggregate_trades",
                    models.BooleanField(
                        default=False,
                        help_text="Should trades be aggregated?",
                        verbose_name="aggregate trades",
                    ),
                ),
                (
                    "symbol_type",
                    models.CharField(
                        choices=[
                            ("spot", "spot"),
                            ("perp", "perp"),
                            ("future", "future"),
                        ],
                        max_length=255,
                        verbose_name="type",
                    ),
                ),
                (
                    "currency_divisor",
                    models.PositiveIntegerField(
                        default=1, verbose_name="currency divisor"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "code_name",
                    models.SlugField(
                        default="", max_length=255, verbose_name="code name"
                    ),
                ),
            ],
            options={
                "verbose_name": "symbol",
                "verbose_name_plural": "symbols",
                "db_table": "quant_candles_symbol",
                "ordering": ("exchange", "api_symbol"),
                "unique_together": set(),
            },
        ),
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_name",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="code name"
                    ),
                ),
                ("date_from", models.DateField(null=True, verbose_name="date from")),
                ("date_to", models.DateField(null=True, verbose_name="date to")),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "symbols",
                    models.ManyToManyField(
                        db_table="quant_candles_candle_symbol",
                        to="quant_tick.symbol",
                        verbose_name="symbols",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "candle",
                "verbose_name_plural": "candles",
                "db_table": "quant_candles_candle",
            },
        ),
        migrations.CreateModel(
            name="AdaptiveCandle",
            fields=[],
            options={
                "verbose_name": "adaptive candle",
                "verbose_name_plural": "adaptive candles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.candle",),
        ),
        migrations.CreateModel(
            name="ConstantCandle",
            fields=[],
            options={
                "verbose_name": "constant candle",
                "verbose_name_plural": "constant candles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.candle",),
        ),
        migrations.CreateModel(
            name="ImbalanceCandle",
            fields=[],
            options={
                "verbose_name": "imbalance candle",
                "verbose_name_plural": "imbalance candles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.candle",),
        ),
        migrations.CreateModel(
            name="RunCandle",
            fields=[],
            options={
                "verbose_name": "run candle",
                "verbose_name_plural": "run candles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.candle",),
        ),
        migrations.CreateModel(
            name="TimeBasedCandle",
            fields=[],
            options={
                "verbose_name": "time based candle",
                "verbose_name_plural": "time based candles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.candle",),
        ),
        migrations.CreateModel(
            name="CandleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quant_tick.candle",
                        verbose_name="candle",
                    ),
                ),
            ],
            options={
                "verbose_name": "candle data",
                "verbose_name_plural": "candle data",
                "db_table": "quant_candles_candle_data",
                "ordering": ("timestamp",),
            },
        ),
        migrations.CreateModel(
            name="TradeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "uid",
                    models.CharField(blank=True, max_length=255, verbose_name="uid"),
                ),
                (
                    "file_data",
                    models.FileField(
                        blank=True, upload_to=fake, verbose_name="file data"
                    ),
                ),
                (
                    "ok",
                    models.BooleanField(
                        db_index=True, default=False, null=True, verbose_name="ok"
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_data",
                        to="quant_tick.symbol",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        choices=[(1, "Minute"), (60, "Hour")],
                        db_index=True,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
            ],
            options={
                "verbose_name": "trade data",
                "verbose_name_plural": "trade data",
                "db_table": "quant_candles_trade_data",
                "ordering": ("timestamp",),
            },
        ),
        migrations.CreateModel(
            name="TradeDataSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "file_data",
                    models.FileField(
                        blank=True, upload_to=fake, verbose_name="file data"
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_data_summary",
                        to="quant_tick.symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "trade data summary",
                "verbose_name_plural": "trade data summary",
                "db_table": "quant_candles_trade_data_summary",
                "ordering": ("date",),
                "unique_together": {("symbol", "date")},
            },
        ),
        migrations.CreateModel(
            name="CandleCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Minute"),
                            (60, "Hour"),
                            (1440, "Day"),
                            (10080, "Week"),
                        ],
                        db_index=True,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="quant_tick.candle",
                    ),
                ),
            ],
            options={
                "verbose_name": "candle cache",
                "verbose_name_plural": "candle cache",
                "db_table": "quant_candles_candle_cache",
                "ordering": ("timestamp",),
            },
        ),
        migrations.AddField(
            model_name="symbol",
            name="recent_error_at",
            field=models.DateTimeField(
                help_text="If there was a recent API error, for example due to exchange maintenance, then backoff.",
                null=True,
                verbose_name="recent API error",
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="significant_trade_filter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="All trades less than the value of the significant trade filter will be aggregated, according to the the algorithm described in the documentation.",
                verbose_name="significant trade filter",
            ),
        ),
        migrations.RenameField(
            model_name="symbol",
            old_name="aggregate_trades",
            new_name="save_aggregated",
        ),
        migrations.AddField(
            model_name="symbol",
            name="save_clustered",
            field=models.BooleanField(
                default=True,
                help_text="Save clustered data?",
                verbose_name="save clustered",
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="save_filtered",
            field=models.BooleanField(
                default=False,
                help_text="Save filtered data?",
                verbose_name="save filtered",
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="save_raw",
            field=models.BooleanField(
                default=False, help_text="Save raw data?", verbose_name="save raw"
            ),
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="currency_divisor",
        ),
        migrations.AlterField(
            model_name="symbol",
            name="code_name",
            field=models.SlugField(
                max_length=255, unique=True, verbose_name="code name"
            ),
        ),
        migrations.RenameField(
            model_name="tradedata",
            old_name="file_data",
            new_name="filtered_data",
        ),
        migrations.AlterField(
            model_name="tradedata",
            name="filtered_data",
            field=models.FileField(
                blank=True,
                upload_to=quant_tick.models.trades.upload_filtered_data_to,
                verbose_name="filtered data",
            ),
        ),
        migrations.AddField(
            model_name="tradedata",
            name="aggregated_data",
            field=models.FileField(
                blank=True,
                upload_to=quant_tick.models.trades.upload_aggregated_data_to,
                verbose_name="aggregated data",
            ),
        ),
        migrations.AddField(
            model_name="tradedata",
            name="candle_data",
            field=models.FileField(
                blank=True,
                upload_to=quant_tick.models.trades.upload_candle_data_to,
                verbose_name="candle data",
            ),
        ),
        migrations.AddField(
            model_name="tradedata",
            name="clustered_data",
            field=models.FileField(
                blank=True, upload_to=fake, verbose_name="clustered data"
            ),
        ),
        migrations.AddField(
            model_name="tradedata",
            name="raw_data",
            field=models.FileField(
                blank=True,
                upload_to=quant_tick.models.trades.upload_raw_data_to,
                verbose_name="raw data",
            ),
        ),
        migrations.AlterField(
            model_name="tradedata",
            name="frequency",
            field=models.PositiveIntegerField(
                choices=[(1, "Minute"), (60, "Hour")],
                db_index=True,
                verbose_name="frequency",
            ),
        ),
        migrations.DeleteModel(
            name="TradeDataSummary",
        ),
        migrations.AlterUniqueTogether(
            name="tradedata",
            unique_together={("symbol", "timestamp", "frequency")},
        ),
        migrations.AlterField(
            model_name="candle",
            name="symbols",
            field=models.ManyToManyField(
                db_table="quant_tick_candle_symbol",
                to="quant_tick.symbol",
                verbose_name="symbols",
            ),
        ),
        migrations.AlterModelTable(
            name="candle",
            table="quant_tick_candle",
        ),
        migrations.AlterModelTable(
            name="candlecache",
            table="quant_tick_candle_cache",
        ),
        migrations.AlterModelTable(
            name="candledata",
            table="quant_tick_candle_data",
        ),
        migrations.AlterModelTable(
            name="globalsymbol",
            table="quant_tick_global_symbol",
        ),
        migrations.AlterModelTable(
            name="symbol",
            table="quant_tick_symbol",
        ),
        migrations.AlterModelTable(
            name="tradedata",
            table="quant_tick_trade_data",
        ),
        migrations.AlterField(
            model_name="symbol",
            name="exchange",
            field=models.CharField(
                choices=[
                    ("binance", "Binance"),
                    ("bitfinex", "Bitfinex"),
                    ("bitmex", "BitMEX"),
                    ("coinbase", "Coinbase"),
                    ("drift", "Drift"),
                    ("hyperliquid", "Hyperliquid"),
                ],
                max_length=255,
                verbose_name="exchange",
            ),
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_name",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="code name"
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quant_tick.candle",
                        verbose_name="candle",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "strategy",
                "verbose_name_plural": "strategies",
                "db_table": "quant_tick_strategy",
            },
        ),
        migrations.CreateModel(
            name="MACrossoverStrategy",
            fields=[],
            options={
                "verbose_name": "ma crossover strategy",
                "verbose_name_plural": "ma crossover strategies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.strategy",),
        ),
        migrations.CreateModel(
            name="StrategyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "file_data",
                    models.FileField(
                        blank=True, upload_to=fake, verbose_name="file data"
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_data",
                        to="quant_tick.strategy",
                        verbose_name="strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "strategy data",
                "verbose_name_plural": "strategy data",
                "db_table": "quant_tick_strategy_data",
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "close_candle_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="quant_tick.candledata",
                        verbose_name="candle data",
                    ),
                ),
                (
                    "open_candle_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="quant_tick.candledata",
                        verbose_name="candle data",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="quant_tick.strategy",
                        verbose_name="strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "signal",
                "verbose_name_plural": "signals",
                "db_table": "quant_tick_signal",
                "ordering": ("open_candle_data__timestamp",),
            },
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="save_clustered",
        ),
        migrations.RemoveField(
            model_name="tradedata",
            name="clustered_data",
        ),
        migrations.AlterField(
            model_name="symbol",
            name="save_filtered",
            field=models.BooleanField(
                default=True,
                help_text="Save filtered data?",
                verbose_name="save filtered",
            ),
        ),
        migrations.CreateModel(
            name="FeatureData",
            fields=[
                (
                    "candle_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="feature_data",
                        serialize=False,
                        to="quant_tick.candledata",
                        verbose_name="candle data",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        help_text="Computed feature vector (realizedVol, volRatio, etc.)",
                        verbose_name="json data",
                    ),
                ),
                (
                    "schema_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of sorted feature column names for drift detection",
                        max_length=16,
                        verbose_name="schema hash",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "feature data",
                "verbose_name_plural": "feature data",
                "db_table": "quant_tick_feature_data",
                "ordering": ("candle_data__timestamp",),
            },
        ),
        migrations.CreateModel(
            name="MLArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        help_text="upper or lower",
                        max_length=20,
                        verbose_name="model type",
                    ),
                ),
                (
                    "artifact",
                    models.FileField(
                        upload_to=fake,
                        verbose_name="artifact",
                    ),
                ),
                (
                    "brier_score",
                    models.FloatField(
                        blank=True,
                        help_text="Cross-validation metric",
                        null=True,
                        verbose_name="brier score",
                    ),
                ),
                (
                    "feature_columns",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=list,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        help_text="Ordered list of feature column names",
                        verbose_name="feature columns",
                    ),
                ),
                (
                    "is_production",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this model is deployed to quant_horizon",
                        verbose_name="is production",
                    ),
                ),
                (
                    "gcs_path",
                    models.CharField(
                        blank=True,
                        help_text="GCS path: gs://bucket/path/model.joblib",
                        max_length=512,
                        verbose_name="gcs path",
                    ),
                ),
                (
                    "sha256",
                    models.CharField(blank=True, max_length=64, verbose_name="sha256"),
                ),
                (
                    "calibrator",
                    models.BinaryField(
                        blank=True,
                        help_text="Deprecated: calibrator is stored in joblib artifact. This field is redundant and not used by inference.",
                        null=True,
                        verbose_name="calibrator",
                    ),
                ),
                (
                    "horizon",
                    models.IntegerField(
                        blank=True,
                        help_text="Horizon in bars, for per-horizon models.",
                        null=True,
                        verbose_name="horizon",
                    ),
                ),
                (
                    "calibration_method",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("isotonic", "Isotonic"),
                            ("platt", "Platt"),
                        ],
                        default="none",
                        help_text="Calibration method.",
                        max_length=20,
                        verbose_name="calibration method",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        help_text="Data including base rates, calibration drift, etc.",
                        verbose_name="json data",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml artifact",
                "verbose_name_plural": "ml artifacts",
                "db_table": "quant_tick_ml_artifact",
            },
        ),
        migrations.CreateModel(
            name="MLConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_name",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="code name"
                    ),
                ),
                (
                    "inference_lookback",
                    models.IntegerField(
                        default=100,
                        help_text="Number of bars to fetch for inference feature computation",
                        verbose_name="inference lookback",
                    ),
                ),
                (
                    "horizon_bars",
                    models.IntegerField(
                        default=180,
                        help_text="Number of bars for touch prediction horizon",
                        verbose_name="horizon bars",
                    ),
                ),
                (
                    "touch_tolerance",
                    models.FloatField(
                        default=0.15,
                        help_text="Max acceptable P(touch) for valid config. Lower = conservative (LP), Higher = aggressive (perp)",
                        verbose_name="touch tolerance",
                    ),
                ),
                (
                    "min_hold_bars",
                    models.IntegerField(
                        default=15,
                        help_text="Minimum bars before position change",
                        verbose_name="min hold bars",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
                (
                    "last_processed_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last processed bar for idempotency",
                        null=True,
                        verbose_name="last processed timestamp",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="active"),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_config",
                        to="quant_tick.candle",
                        verbose_name="candle",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml config",
                "verbose_name_plural": "ml config",
                "db_table": "quant_tick_ml_config",
            },
        ),
        migrations.CreateModel(
            name="MLSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "lower_bound",
                    models.FloatField(
                        help_text="Lower bound as fraction of entry price (e.g., -0.03)",
                        verbose_name="lower bound",
                    ),
                ),
                (
                    "upper_bound",
                    models.FloatField(
                        help_text="Upper bound as fraction of entry price (e.g., 0.05)",
                        verbose_name="upper bound",
                    ),
                ),
                (
                    "borrow_ratio",
                    models.FloatField(
                        help_text="Borrow ratio for DBI (0.5 = balanced)",
                        verbose_name="borrow ratio",
                    ),
                ),
                ("p_touch_lower", models.FloatField(verbose_name="P(touch lower)")),
                ("p_touch_upper", models.FloatField(verbose_name="P(touch upper)")),
                (
                    "json_data",
                    models.JSONField(
                        blank=True,
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml signal",
                "verbose_name_plural": "ml signals",
                "db_table": "quant_tick_ml_signal",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("backtest", "backtest"),
                            ("paper", "paper"),
                            ("live", "live"),
                        ],
                        default="backtest",
                        max_length=20,
                        verbose_name="position type",
                    ),
                ),
                (
                    "lower_bound",
                    models.FloatField(
                        help_text="Lower bound as fraction of entry price (e.g., -0.03)",
                        verbose_name="lower bound",
                    ),
                ),
                (
                    "upper_bound",
                    models.FloatField(
                        help_text="Upper bound as fraction of entry price (e.g., 0.05)",
                        verbose_name="upper bound",
                    ),
                ),
                (
                    "borrow_ratio",
                    models.FloatField(
                        help_text="Asset allocation (0.5 = balanced, >0.5 = bearish, <0.5 = bullish)",
                        verbose_name="borrow ratio",
                    ),
                ),
                (
                    "entry_timestamp",
                    models.DateTimeField(db_index=True, verbose_name="entry timestamp"),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=38, max_digits=76, verbose_name="entry price"
                    ),
                ),
                (
                    "exit_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="exit timestamp"
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=38,
                        max_digits=76,
                        null=True,
                        verbose_name="exit price",
                    ),
                ),
                (
                    "exit_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("touched_lower", "touched lower"),
                            ("touched_upper", "touched upper"),
                            ("rebalanced", "rebalanced"),
                            ("max_duration", "max duration"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="exit reason",
                    ),
                ),
                (
                    "bars_held",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of bars position was held",
                        null=True,
                        verbose_name="bars held",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("open", "open"),
                            ("closed", "closed"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        blank=True,
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        help_text="Additional data: p_touch_lower, p_touch_upper, width, asymmetry",
                        null=True,
                        verbose_name="json data",
                    ),
                ),
            ],
            options={
                "verbose_name": "position",
                "verbose_name_plural": "positions",
                "db_table": "quant_tick_position",
                "ordering": ["-entry_timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="ImbalanceCandle",
        ),
        migrations.DeleteModel(
            name="RunCandle",
        ),
        migrations.AlterField(
            model_name="symbol",
            name="symbol_type",
            field=models.CharField(
                choices=[("spot", "spot"), ("perp", "perp")],
                max_length=255,
                verbose_name="type",
            ),
        ),
        migrations.AddField(
            model_name="mlconfig",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ml_config",
                to="quant_tick.symbol",
                verbose_name="symbol",
            ),
        ),
        migrations.AddField(
            model_name="mlartifact",
            name="ml_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ml_artifacts",
                to="quant_tick.mlconfig",
                verbose_name="ml config",
            ),
        ),
        migrations.AddField(
            model_name="mlsignal",
            name="ml_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ml_signals",
                to="quant_tick.mlconfig",
                verbose_name="ml config",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="ml_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="quant_tick.mlconfig",
                verbose_name="ml config",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="ml_signal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="quant_tick.mlsignal",
                verbose_name="ml signal",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="quant_tick.symbol",
                verbose_name="symbol",
            ),
        ),
        migrations.AddConstraint(
            model_name="mlartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_production", True)),
                fields=("ml_config",),
                name="unique_production_model_per_config",
            ),
        ),
        migrations.AddIndex(
            model_name="mlsignal",
            index=models.Index(
                fields=["ml_config", "timestamp"], name="quant_tick__ml_conf_a14ed1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["ml_config", "position_type"],
                name="quant_tick__ml_conf_741d47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["position_type", "status"],
                name="quant_tick__positio_362a47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["entry_timestamp"], name="quant_tick__entry_t_926fe9_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="signal",
            name="close_candle_data",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="open_candle_data",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="candle",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="strategydata",
            name="strategy",
        ),
        migrations.DeleteModel(
            name="MACrossoverStrategy",
        ),
        migrations.DeleteModel(
            name="Signal",
        ),
        migrations.DeleteModel(
            name="Strategy",
        ),
        migrations.DeleteModel(
            name="StrategyData",
        ),
    ]
