# Generated by Django 6.0.3 on 2026-04-08 00:44

import django.db.models.deletion
import quant_tick.models.base
import quant_tick.models.trades
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('quant_tick', '0001_initial_squashed_0005_remove_signal_close_candle_data_and_more'),
        ('quant_tick', '0006_fundingrate_renkodata_signal_strategy_and_more'),
        ('quant_tick', '0007_remove_renkodata_kind_renkodata_parent'),
        ('quant_tick', '0008_remove_candle_symbols_remove_strategy_symbol_and_more'),
        ('quant_tick', '0009_add_renkodata_kind_remove_parent'),
        ('quant_tick', '0010_alter_candle_symbol_alter_tradedata_frequency'),
        ('quant_tick', '0011_remove_renkodata_candle_data_and_more'),
        ('quant_tick', '0012_alter_fundingrate_unique_together_and_more'),
        ('quant_tick', '0013_taskstate'),
        ('quant_tick', '0014_remove_symbol_metadata'),
        ('quant_tick', '0015_symbol_date_from'),
    ]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.SlugField(max_length=255, unique=True, verbose_name='code name')),
                ('exchange', models.CharField(choices=[('binance', 'Binance'), ('bitfinex', 'Bitfinex'), ('bitmex', 'BitMEX'), ('coinbase', 'Coinbase')], max_length=255, verbose_name='exchange')),
                ('api_symbol', models.CharField(max_length=255, verbose_name='API symbol')),
                ('date_from', models.DateField(null=True, verbose_name='date from')),
                ('save_raw', models.BooleanField(default=False, help_text='Save raw data?', verbose_name='save raw')),
                ('save_aggregated', models.BooleanField(default=False, help_text='Should trades be aggregated?', verbose_name='aggregate trades')),
                ('significant_trade_filter', models.PositiveIntegerField(default=0, help_text='All trades less than the value of the significant trade filter will be aggregated, according to the the algorithm described in the documentation.', verbose_name='significant trade filter')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'symbol',
                'verbose_name_plural': 'symbols',
                'db_table': 'quant_tick_symbol',
                'ordering': ('exchange', 'api_symbol'),
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.SlugField(max_length=255, unique=True, verbose_name='code name')),
                ('date_from', models.DateField(null=True, verbose_name='date from')),
                ('date_to', models.DateField(null=True, verbose_name='date to')),
                ('json_data', models.JSONField(decoder=quant_tick.models.base.QuantTickDecoder, default=dict, encoder=quant_tick.models.base.QuantTickEncoder, verbose_name='json data')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quant_tick.symbol', verbose_name='symbol')),
            ],
            options={
                'verbose_name': 'candle',
                'verbose_name_plural': 'candles',
                'db_table': 'quant_tick_candle',
            },
        ),
        migrations.CreateModel(
            name='ConstantCandle',
            fields=[
            ],
            options={
                'verbose_name': 'constant candle',
                'verbose_name_plural': 'constant candles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quant_tick.candle',),
        ),
        migrations.CreateModel(
            name='TimeBasedCandle',
            fields=[
            ],
            options={
                'verbose_name': 'time based candle',
                'verbose_name_plural': 'time based candles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quant_tick.candle',),
        ),
        migrations.CreateModel(
            name='CandleCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='timestamp')),
                ('frequency', models.PositiveIntegerField(db_index=True, verbose_name='frequency')),
                ('json_data', models.JSONField(decoder=quant_tick.models.base.QuantTickDecoder, default=dict, encoder=quant_tick.models.base.QuantTickEncoder, verbose_name='json data')),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='quant_tick.candle')),
            ],
            options={
                'verbose_name': 'candle cache',
                'verbose_name_plural': 'candle cache',
                'db_table': 'quant_tick_candle_cache',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='CandleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='timestamp')),
                ('open', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='open')),
                ('high', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='high')),
                ('low', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='low')),
                ('close', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='close')),
                ('volume', models.DecimalField(decimal_places=38, max_digits=76, verbose_name='volume')),
                ('buy_volume', models.DecimalField(decimal_places=38, max_digits=76, verbose_name='buy volume')),
                ('notional', models.DecimalField(decimal_places=38, max_digits=76, verbose_name='notional')),
                ('buy_notional', models.DecimalField(decimal_places=38, max_digits=76, verbose_name='buy notional')),
                ('ticks', models.PositiveIntegerField(verbose_name='ticks')),
                ('buy_ticks', models.PositiveIntegerField(verbose_name='buy ticks')),
                ('realized_variance', models.DecimalField(decimal_places=38, max_digits=76, verbose_name='realized variance')),
                ('incomplete', models.BooleanField(default=False, verbose_name='incomplete')),
                ('extra_data', models.JSONField(decoder=quant_tick.models.base.QuantTickDecoder, default=dict, encoder=quant_tick.models.base.QuantTickEncoder, verbose_name='extra data')),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quant_tick.candle', verbose_name='candle')),
            ],
            options={
                'verbose_name': 'candle data',
                'verbose_name_plural': 'candle data',
                'db_table': 'quant_tick_candle_data',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(blank=True, choices=[('binance', 'Binance'), ('bitfinex', 'Bitfinex'), ('bitmex', 'BitMEX'), ('coinbase', 'Coinbase')], default='', max_length=255, verbose_name='exchange')),
                ('task_type', models.CharField(choices=[('aggregate_trades', 'Aggregate trades'), ('aggregate_candles', 'Aggregate candles')], max_length=255, verbose_name='task type')),
                ('recent_error_at', models.DateTimeField(blank=True, help_text='Last task error time used for observability.', null=True, verbose_name='recent error')),
                ('recent_error_count', models.PositiveIntegerField(default=0, help_text='Consecutive task errors used to determine exponential backoff.', verbose_name='recent error count')),
                ('next_fetch_at', models.DateTimeField(blank=True, help_text='Do not run this task before this time if backoff is active.', null=True, verbose_name='next fetch at')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Lease expiry for preventing overlapping task runs.', null=True, verbose_name='locked until')),
            ],
            options={
                'verbose_name': 'task state',
                'verbose_name_plural': 'task states',
                'db_table': 'quant_tick_task_state',
                'ordering': ('task_type', 'exchange'),
                'constraints': [models.UniqueConstraint(fields=('task_type', 'exchange'), name='quant_tick_task_state_unique')],
            },
        ),
        migrations.CreateModel(
            name='AdaptiveCandle',
            fields=[
            ],
            options={
                'verbose_name': 'adaptive candle',
                'verbose_name_plural': 'adaptive candles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quant_tick.constantcandle',),
        ),
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='timestamp')),
                ('uid', models.CharField(blank=True, max_length=255, verbose_name='uid')),
                ('frequency', models.PositiveIntegerField(choices=[(1, 'Minute'), (60, 'Hour'), (1440, 'Day')], db_index=True, verbose_name='frequency')),
                ('raw_data', models.FileField(blank=True, upload_to=quant_tick.models.trades.upload_raw_data_to, verbose_name='raw data')),
                ('aggregated_data', models.FileField(blank=True, upload_to=quant_tick.models.trades.upload_aggregated_data_to, verbose_name='aggregated data')),
                ('filtered_data', models.FileField(blank=True, upload_to=quant_tick.models.trades.upload_filtered_data_to, verbose_name='filtered data')),
                ('json_data', models.JSONField(decoder=quant_tick.models.base.QuantTickDecoder, encoder=quant_tick.models.base.QuantTickEncoder, null=True, verbose_name='json data')),
                ('ok', models.BooleanField(db_index=True, default=False, null=True, verbose_name='ok')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_data', to='quant_tick.symbol')),
            ],
            options={
                'verbose_name': 'trade data',
                'verbose_name_plural': 'trade data',
                'db_table': 'quant_tick_trade_data',
                'ordering': ('timestamp',),
                'unique_together': {('symbol', 'timestamp', 'frequency')},
            },
        ),
    ]
