# Generated by Django 5.0.1 on 2024-01-29 13:23

import django.db.migrations.operations.special
import django.db.models.deletion
import randomname
from django.db import migrations, models

import quant_tick.models.base
import quant_tick.models.trades


def fake(*args):
    pass


def get_random_name(apps, schema_editor):
    Symbol = apps.get_model("quant_tick", "Symbol")
    for symbol in Symbol.objects.all():
        symbol.code_name = randomname.get_name()
        symbol.save()


class Migration(migrations.Migration):
    replaces = [
        (
            "quant_tick",
            "0001_squashed_0004_alter_candle_symbols_alter_candle_table_and_more.py",
        ),
    ]

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "global symbol",
                "verbose_name_plural": "global symbols",
                "db_table": "quant_candles_global_symbol",
            },
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("binance", "Binance"),
                            ("bitfinex", "Bitfinex"),
                            ("bitmex", "BitMEX"),
                            ("bybit", "Bybit"),
                            ("coinbase", "Coinbase"),
                        ],
                        max_length=255,
                        verbose_name="exchange",
                    ),
                ),
                (
                    "api_symbol",
                    models.CharField(max_length=255, verbose_name="API symbol"),
                ),
                (
                    "significant_trade_filter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="If trades are aggregated, they can be further filtered according to the algorithm described in the documentation.",
                        verbose_name="significant trade filter",
                    ),
                ),
                (
                    "global_symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbols",
                        to="quant_tick.globalsymbol",
                    ),
                ),
                (
                    "aggregate_trades",
                    models.BooleanField(
                        default=False,
                        help_text="Should trades be aggregated?",
                        verbose_name="aggregate trades",
                    ),
                ),
                (
                    "symbol_type",
                    models.CharField(
                        choices=[
                            ("spot", "spot"),
                            ("perp", "perp"),
                            ("future", "future"),
                        ],
                        max_length=255,
                        verbose_name="type",
                    ),
                ),
                (
                    "currency_divisor",
                    models.PositiveIntegerField(
                        default=1, verbose_name="currency divisor"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "code_name",
                    models.SlugField(
                        default="", max_length=255, verbose_name="code name"
                    ),
                ),
            ],
            options={
                "verbose_name": "symbol",
                "verbose_name_plural": "symbols",
                "db_table": "quant_candles_symbol",
                "ordering": ("exchange", "api_symbol"),
                "unique_together": set(),
            },
        ),
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_name",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="code name"
                    ),
                ),
                ("date_from", models.DateField(null=True, verbose_name="date from")),
                ("date_to", models.DateField(null=True, verbose_name="date to")),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "symbols",
                    models.ManyToManyField(
                        db_table="quant_candles_candle_symbol",
                        to="quant_tick.symbol",
                        verbose_name="symbols",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "candle",
                "verbose_name_plural": "candles",
                "db_table": "quant_candles_candle",
            },
        ),
        migrations.CreateModel(
            name="AdaptiveCandle",
            fields=[],
            options={
                "verbose_name": "adaptive candle",
                "verbose_name_plural": "adaptive candles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.candle",),
        ),
        migrations.CreateModel(
            name="ConstantCandle",
            fields=[],
            options={
                "verbose_name": "constant candle",
                "verbose_name_plural": "constant candles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.candle",),
        ),
        migrations.CreateModel(
            name="ImbalanceCandle",
            fields=[],
            options={
                "verbose_name": "imbalance candle",
                "verbose_name_plural": "imbalance candles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.candle",),
        ),
        migrations.CreateModel(
            name="RunCandle",
            fields=[],
            options={
                "verbose_name": "run candle",
                "verbose_name_plural": "run candles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.candle",),
        ),
        migrations.CreateModel(
            name="TimeBasedCandle",
            fields=[],
            options={
                "verbose_name": "time based candle",
                "verbose_name_plural": "time based candles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.candle",),
        ),
        migrations.CreateModel(
            name="CandleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quant_tick.candle",
                        verbose_name="candle",
                    ),
                ),
            ],
            options={
                "verbose_name": "candle data",
                "verbose_name_plural": "candle data",
                "db_table": "quant_candles_candle_data",
                "ordering": ("timestamp",),
            },
        ),
        migrations.CreateModel(
            name="TradeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "uid",
                    models.CharField(blank=True, max_length=255, verbose_name="uid"),
                ),
                (
                    "file_data",
                    models.FileField(
                        blank=True, upload_to=fake, verbose_name="file data"
                    ),
                ),
                (
                    "ok",
                    models.BooleanField(
                        db_index=True, default=False, null=True, verbose_name="ok"
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_data",
                        to="quant_tick.symbol",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        choices=[(1, "Minute"), (60, "Hour")],
                        db_index=True,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
            ],
            options={
                "verbose_name": "trade data",
                "verbose_name_plural": "trade data",
                "db_table": "quant_candles_trade_data",
                "ordering": ("timestamp",),
            },
        ),
        migrations.CreateModel(
            name="TradeDataSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "file_data",
                    models.FileField(
                        blank=True, upload_to=fake, verbose_name="file data"
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_data_summary",
                        to="quant_tick.symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "trade data summary",
                "verbose_name_plural": "trade data summary",
                "db_table": "quant_candles_trade_data_summary",
                "ordering": ("date",),
                "unique_together": {("symbol", "date")},
            },
        ),
        migrations.CreateModel(
            name="CandleCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Minute"),
                            (60, "Hour"),
                            (1440, "Day"),
                            (10080, "Week"),
                        ],
                        db_index=True,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="quant_tick.candle",
                    ),
                ),
            ],
            options={
                "verbose_name": "candle cache",
                "verbose_name_plural": "candle cache",
                "db_table": "quant_candles_candle_cache",
                "ordering": ("timestamp",),
            },
        ),
        migrations.RunPython(
            code=get_random_name,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="symbol",
            name="recent_error_at",
            field=models.DateTimeField(
                help_text="If there was a recent API error, for example due to exchange maintenance, then backoff.",
                null=True,
                verbose_name="recent API error",
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="significant_trade_filter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="All trades less than the value of the significant trade filter will be aggregated, according to the the algorithm described in the documentation.",
                verbose_name="significant trade filter",
            ),
        ),
        migrations.RenameField(
            model_name="symbol",
            old_name="aggregate_trades",
            new_name="save_aggregated",
        ),
        migrations.AddField(
            model_name="symbol",
            name="save_clustered",
            field=models.BooleanField(
                default=True,
                help_text="Save clustered data?",
                verbose_name="save clustered",
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="save_filtered",
            field=models.BooleanField(
                default=False,
                help_text="Save filtered data?",
                verbose_name="save filtered",
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="save_raw",
            field=models.BooleanField(
                default=False, help_text="Save raw data?", verbose_name="save raw"
            ),
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="currency_divisor",
        ),
        migrations.AlterField(
            model_name="symbol",
            name="code_name",
            field=models.SlugField(
                max_length=255, unique=True, verbose_name="code name"
            ),
        ),
        migrations.RenameField(
            model_name="tradedata",
            old_name="file_data",
            new_name="filtered_data",
        ),
        migrations.AlterField(
            model_name="tradedata",
            name="filtered_data",
            field=models.FileField(
                blank=True,
                upload_to=quant_tick.models.trades.upload_filtered_data_to,
                verbose_name="filtered data",
            ),
        ),
        migrations.AddField(
            model_name="tradedata",
            name="aggregated_data",
            field=models.FileField(
                blank=True,
                upload_to=quant_tick.models.trades.upload_aggregated_data_to,
                verbose_name="aggregated data",
            ),
        ),
        migrations.AddField(
            model_name="tradedata",
            name="candle_data",
            field=models.FileField(
                blank=True,
                upload_to=quant_tick.models.trades.upload_candle_data_to,
                verbose_name="candle data",
            ),
        ),
        migrations.AddField(
            model_name="tradedata",
            name="clustered_data",
            field=models.FileField(
                blank=True,
                upload_to=quant_tick.models.trades.upload_clustered_data_to,
                verbose_name="clustered data",
            ),
        ),
        migrations.AddField(
            model_name="tradedata",
            name="raw_data",
            field=models.FileField(
                blank=True,
                upload_to=quant_tick.models.trades.upload_raw_data_to,
                verbose_name="raw data",
            ),
        ),
        migrations.AlterField(
            model_name="tradedata",
            name="frequency",
            field=models.PositiveIntegerField(
                choices=[(1, "Minute"), (60, "Hour"), (1440, "Day")],
                db_index=True,
                verbose_name="frequency",
            ),
        ),
        migrations.DeleteModel(
            name="TradeDataSummary",
        ),
        migrations.AlterUniqueTogether(
            name="tradedata",
            unique_together={("symbol", "timestamp", "frequency")},
        ),
        migrations.AlterField(
            model_name="candle",
            name="symbols",
            field=models.ManyToManyField(
                db_table="quant_tick_candle_symbol",
                to="quant_tick.symbol",
                verbose_name="symbols",
            ),
        ),
        migrations.AlterModelTable(
            name="candle",
            table="quant_tick_candle",
        ),
        migrations.AlterModelTable(
            name="candlecache",
            table="quant_tick_candle_cache",
        ),
        migrations.AlterModelTable(
            name="candledata",
            table="quant_tick_candle_data",
        ),
        migrations.AlterModelTable(
            name="globalsymbol",
            table="quant_tick_global_symbol",
        ),
        migrations.AlterModelTable(
            name="symbol",
            table="quant_tick_symbol",
        ),
        migrations.AlterModelTable(
            name="tradedata",
            table="quant_tick_trade_data",
        ),
    ]
