# Generated by Codex on 2026-05-05

import django.db.models.deletion
import quant_tick.models.base
from django.db import migrations, models


EXCHANGE_CHOICES = [
    ("binance", "Binance"),
    ("binance-futures", "Binance Futures"),
    ("bitfinex", "Bitfinex"),
    ("bitmex", "BitMEX"),
    ("coinbase", "Coinbase"),
    ("hyperliquid", "Hyperliquid"),
]


SYMBOL_TYPE_CHOICES = [
    ("spot", "Spot"),
    ("perpetual", "Perpetual"),
]


TASK_TYPE_CHOICES = [
    ("aggregate_trades", "Aggregate trades"),
    ("aggregate_candles", "Aggregate candles"),
    ("fetch_exchange_data", "Fetch exchange data"),
]


def set_symbol_types(apps, schema_editor):
    Symbol = apps.get_model("quant_tick", "Symbol")
    Symbol.objects.filter(exchange__in=("binance", "bitfinex", "coinbase")).update(
        symbol_type="spot"
    )
    Symbol.objects.filter(exchange="bitmex").update(symbol_type="perpetual")


class Migration(migrations.Migration):

    replaces = [
        ("quant_tick", "0002_symbol_symbol_type"),
        ("quant_tick", "0003_market_data"),
        ("quant_tick", "0004_remove_coinbase_advanced"),
    ]

    dependencies = [
        ("quant_tick", "0001_initial_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="symbol_type",
            field=models.CharField(
                choices=SYMBOL_TYPE_CHOICES,
                default="spot",
                max_length=32,
                verbose_name="symbol type",
            ),
        ),
        migrations.RunPython(set_symbol_types, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="symbol",
            name="exchange",
            field=models.CharField(
                choices=EXCHANGE_CHOICES,
                max_length=255,
                verbose_name="exchange",
            ),
        ),
        migrations.AlterField(
            model_name="taskstate",
            name="exchange",
            field=models.CharField(
                blank=True,
                choices=EXCHANGE_CHOICES,
                default="",
                max_length=255,
                verbose_name="exchange",
            ),
        ),
        migrations.AlterField(
            model_name="taskstate",
            name="task_type",
            field=models.CharField(
                choices=TASK_TYPE_CHOICES,
                max_length=255,
                verbose_name="task type",
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="exchange_candle_resolution",
            field=models.CharField(
                blank=True,
                default="",
                max_length=16,
                verbose_name="exchange candle resolution",
            ),
        ),
        migrations.CreateModel(
            name="FundingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "funding_rate",
                    models.DecimalField(
                        decimal_places=38,
                        max_digits=76,
                        verbose_name="funding rate",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_data",
                        to="quant_tick.symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "funding data",
                "verbose_name_plural": "funding data",
                "db_table": "quant_tick_funding_data",
                "ordering": ("timestamp",),
                "unique_together": {("symbol", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="ExchangeCandleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        db_index=True,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=38,
                        max_digits=76,
                        verbose_name="open",
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=38,
                        max_digits=76,
                        verbose_name="high",
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=38,
                        max_digits=76,
                        verbose_name="low",
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=38,
                        max_digits=76,
                        verbose_name="close",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=38,
                        max_digits=76,
                        null=True,
                        verbose_name="volume",
                    ),
                ),
                (
                    "notional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=38,
                        max_digits=76,
                        null=True,
                        verbose_name="notional",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_candle_data",
                        to="quant_tick.symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "exchange candle data",
                "verbose_name_plural": "exchange candle data",
                "db_table": "quant_tick_exchange_candle_data",
                "ordering": ("timestamp",),
                "unique_together": {("symbol", "timestamp", "frequency")},
            },
        ),
    ]
