# Generated by Codex on 2026-05-02

from django.db import migrations, models


def forwards(apps, schema_editor):
    Symbol = apps.get_model("quant_tick", "Symbol")
    Symbol.objects.filter(exchange__in=("binance", "bitfinex", "coinbase")).update(
        symbol_type="spot"
    )
    Symbol.objects.filter(exchange="bitmex").update(symbol_type="perpetual")


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0001_initial_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="symbol_type",
            field=models.CharField(
                choices=[("spot", "Spot"), ("perpetual", "Perpetual")],
                default="spot",
                max_length=32,
                verbose_name="symbol type",
            ),
        ),
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
