# Generated by Django 5.2 on 2025-05-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RenkoBrick",
            fields=[],
            options={
                "verbose_name": "renko brick",
                "verbose_name_plural": "renko bricks",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.constantcandle",),
        ),
    ]
