# Generated by Django 5.0 on 2024-01-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_tick', '0001_squashed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='should_aggregate_trades',
            new_name='aggregate_trades',
        ),
        migrations.AlterUniqueTogether(
            name='symbol',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='globalsymbol',
            name='notional',
        ),
        migrations.AddField(
            model_name='symbol',
            name='code_name',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='code name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='recent_error_at',
            field=models.DateTimeField(help_text='If there was a recent API error, for example due to exchange maintenance, then backoff.', null=True, verbose_name='recent API error'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='significant_trade_filter',
            field=models.PositiveIntegerField(default=0, help_text='All trades less than the value of the significant trade filter will be aggregated, according to the the algorithm described in the documentation.', verbose_name='significant trade filter'),
        ),
    ]
