# Generated by Django 5.2 on 2025-08-03 06:55

import django.db.models.deletion
from django.db import migrations, models

import quant_tick.models.base


def fake(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("quant_tick", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="exchange",
            field=models.CharField(
                choices=[
                    ("binance", "Binance"),
                    ("bitfinex", "Bitfinex"),
                    ("bitmex", "BitMEX"),
                    ("coinbase", "Coinbase"),
                ],
                max_length=255,
                verbose_name="exchange",
            ),
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_name",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="code name"
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quant_tick.candle",
                        verbose_name="candle",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "strategy",
                "verbose_name_plural": "strategies",
                "db_table": "quant_tick_strategy",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "close_candle_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="close_positions",
                        to="quant_tick.candledata",
                        verbose_name="candle data",
                    ),
                ),
                (
                    "open_candle_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_positions",
                        to="quant_tick.candledata",
                        verbose_name="candle data",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="quant_tick.strategy",
                        verbose_name="strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "position",
                "verbose_name_plural": "positions",
                "db_table": "quant_tick_position",
            },
        ),
        migrations.CreateModel(
            name="MACrossoverStrategy",
            fields=[],
            options={
                "verbose_name": "ma crossover strategy",
                "verbose_name_plural": "ma crossover strategies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.strategy",),
        ),
        migrations.CreateModel(
            name="StrategyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "file_data",
                    models.FileField(
                        blank=True,
                        upload_to=fake,
                        verbose_name="file data",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_data",
                        to="quant_tick.strategy",
                        verbose_name="strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "strategy data",
                "verbose_name_plural": "strategy data",
                "db_table": "quant_tick_strategy_data",
            },
        ),
    ]
