# Generated by Django 5.0 on 2024-01-01 23:50
import randomname
from django.db import migrations, models


def get_random_name(apps, schema_editor):
    Symbol = apps.get_model("quant_tick", "Symbol")
    for symbol in Symbol.objects.all():
        symbol.code_name = randomname.get_name()
        symbol.save()


class Migration(migrations.Migration):
    dependencies = [
        ("quant_tick", "0001_squashed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalsymbol",
            name="notional",
        ),
        migrations.AlterUniqueTogether(
            name="symbol",
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name="symbol",
            old_name="should_aggregate_trades",
            new_name="aggregate_trades",
        ),
        migrations.AddField(
            model_name="symbol",
            name="code_name",
            field=models.SlugField(
                default="",
                max_length=255,
                verbose_name="code name",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(get_random_name, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="symbol",
            name="recent_error_at",
            field=models.DateTimeField(
                help_text="If there was a recent API error, for example due to exchange maintenance, then backoff.",
                null=True,
                verbose_name="recent API error",
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="significant_trade_filter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="All trades less than the value of the significant trade filter will be aggregated, according to the the algorithm described in the documentation.",
                verbose_name="significant trade filter",
            ),
        ),
        migrations.RenameField(
            model_name="symbol",
            old_name="aggregate_trades",
            new_name="save_aggregated",
        ),
        migrations.AddField(
            model_name="symbol",
            name="save_clustered",
            field=models.BooleanField(
                default=True,
                help_text="Save clustered data?",
                verbose_name="save clustered",
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="save_filtered",
            field=models.BooleanField(
                default=False,
                help_text="Save filtered data?",
                verbose_name="save filtered",
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="save_raw",
            field=models.BooleanField(
                default=False, help_text="Save raw data?", verbose_name="save raw"
            ),
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="currency_divisor",
        ),
    ]
