# Generated by Django 4.1.5 on 2023-01-22 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quant_tick", "0002_candlereadonlydata_timebasedcandle_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tradedatasummary",
            unique_together={("symbol", "date")},
        ),
    ]
