# Generated by Codex on 2026-05-09

from django.db import migrations, models


def delete_legacy_task_states(apps, _schema_editor):
    task_state = apps.get_model("quant_tick", "TaskState")
    task_state.objects.filter(api_symbol="").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0002_exchange_data"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="taskstate",
            name="quant_tick_task_state_unique",
        ),
        migrations.AddField(
            model_name="taskstate",
            name="api_symbol",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="API symbol",
            ),
        ),
        migrations.RunPython(
            delete_legacy_task_states,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="taskstate",
            name="exchange",
            field=models.CharField(
                choices=[
                    ("binance", "Binance"),
                    ("binance-futures", "Binance Futures"),
                    ("bitfinex", "Bitfinex"),
                    ("bitmex", "BitMEX"),
                    ("coinbase", "Coinbase"),
                    ("hyperliquid", "Hyperliquid"),
                ],
                max_length=255,
                verbose_name="exchange",
            ),
        ),
        migrations.AlterField(
            model_name="taskstate",
            name="api_symbol",
            field=models.CharField(max_length=255, verbose_name="API symbol"),
        ),
        migrations.AddConstraint(
            model_name="taskstate",
            constraint=models.UniqueConstraint(
                fields=("task_type", "exchange", "api_symbol"),
                name="quant_tick_task_state_unique",
            ),
        ),
        migrations.AlterModelOptions(
            name="taskstate",
            options={
                "ordering": ("task_type", "exchange", "api_symbol"),
                "verbose_name": "task state",
                "verbose_name_plural": "task states",
            },
        ),
    ]
