# Generated by Codex on 2026-05-04

import django.db.models.deletion
import quant_tick.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0002_symbol_symbol_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="exchange",
            field=models.CharField(
                choices=[
                    ("binance", "Binance"),
                    ("bitfinex", "Bitfinex"),
                    ("bitmex", "BitMEX"),
                    ("coinbase", "Coinbase"),
                    ("hyperliquid", "Hyperliquid"),
                ],
                max_length=255,
                verbose_name="exchange",
            ),
        ),
        migrations.AlterField(
            model_name="taskstate",
            name="exchange",
            field=models.CharField(
                blank=True,
                choices=[
                    ("binance", "Binance"),
                    ("bitfinex", "Bitfinex"),
                    ("bitmex", "BitMEX"),
                    ("coinbase", "Coinbase"),
                    ("hyperliquid", "Hyperliquid"),
                ],
                default="",
                max_length=255,
                verbose_name="exchange",
            ),
        ),
        migrations.AlterField(
            model_name="taskstate",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("aggregate_trades", "Aggregate trades"),
                    ("aggregate_candles", "Aggregate candles"),
                    ("fetch_exchange_data", "Fetch exchange data"),
                ],
                max_length=255,
                verbose_name="task type",
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="exchange_candle_resolution",
            field=models.CharField(
                blank=True,
                default="",
                max_length=16,
                verbose_name="exchange candle resolution",
            ),
        ),
        migrations.CreateModel(
            name="FundingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "funding_rate",
                    models.DecimalField(
                        decimal_places=38,
                        max_digits=76,
                        verbose_name="funding rate",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_data",
                        to="quant_tick.symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "funding data",
                "verbose_name_plural": "funding data",
                "db_table": "quant_tick_funding_data",
                "ordering": ("timestamp",),
                "unique_together": {("symbol", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="ExchangeCandleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        db_index=True,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=38,
                        max_digits=76,
                        verbose_name="open",
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=38,
                        max_digits=76,
                        verbose_name="high",
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=38,
                        max_digits=76,
                        verbose_name="low",
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=38,
                        max_digits=76,
                        verbose_name="close",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=38,
                        max_digits=76,
                        null=True,
                        verbose_name="volume",
                    ),
                ),
                (
                    "notional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=38,
                        max_digits=76,
                        null=True,
                        verbose_name="notional",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_candle_data",
                        to="quant_tick.symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "exchange candle data",
                "verbose_name_plural": "exchange candle data",
                "db_table": "quant_tick_exchange_candle_data",
                "ordering": ("timestamp",),
                "unique_together": {("symbol", "timestamp", "frequency")},
            },
        ),
    ]
