# Generated by Django 5.2.5 on 2025-10-11 03:52

import django.db.models.deletion
import quant_tick.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("quant_tick", "0003_signal_delete_position"),
        ("quant_tick", "0004_remove_symbol_save_clustered_and_more"),
        ("quant_tick", "0005_symbol_save_clustered_tradedata_clustered_data"),
        ("quant_tick", "0006_remove_symbol_save_clustered_and_more"),
    ]

    dependencies = [
        ("quant_tick", "0002_alter_symbol_exchange_strategy_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "close_candle_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="quant_tick.candledata",
                        verbose_name="candle data",
                    ),
                ),
                (
                    "open_candle_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="quant_tick.candledata",
                        verbose_name="candle data",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="quant_tick.strategy",
                        verbose_name="strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "signal",
                "verbose_name_plural": "signals",
                "db_table": "quant_tick_signal",
                "ordering": ("open_candle_data__timestamp",),
            },
        ),
        migrations.DeleteModel(
            name="Position",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="save_clustered",
        ),
        migrations.RemoveField(
            model_name="tradedata",
            name="clustered_data",
        ),
        migrations.AlterField(
            model_name="symbol",
            name="save_filtered",
            field=models.BooleanField(
                default=True,
                help_text="Save filtered data?",
                verbose_name="save filtered",
            ),
        ),
    ]
