# Generated by Codex on 2026-05-09

import quant_tick.models.base
from django.db import migrations, models


EXCHANGE_CHOICES = [
    ("binance", "Binance"),
    ("binance-futures", "Binance Futures"),
    ("bitfinex", "Bitfinex"),
    ("bitmex", "BitMEX"),
    ("coinbase", "Coinbase"),
    ("hyperliquid", "Hyperliquid"),
]


def delete_legacy_task_states(apps, _schema_editor):
    task_state = apps.get_model("quant_tick", "TaskState")
    task_state.objects.filter(api_symbol="").delete()


def json_field(verbose_name, default):
    return models.JSONField(
        blank=True,
        decoder=quant_tick.models.base.QuantTickDecoder,
        default=default,
        encoder=quant_tick.models.base.QuantTickEncoder,
        verbose_name=verbose_name,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0002_exchange_data"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="taskstate",
            name="quant_tick_task_state_unique",
        ),
        migrations.AddField(
            model_name="taskstate",
            name="api_symbol",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="API symbol",
            ),
        ),
        migrations.RunPython(
            delete_legacy_task_states,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="taskstate",
            name="exchange",
            field=models.CharField(
                choices=EXCHANGE_CHOICES,
                max_length=255,
                verbose_name="exchange",
            ),
        ),
        migrations.AlterField(
            model_name="taskstate",
            name="api_symbol",
            field=models.CharField(max_length=255, verbose_name="API symbol"),
        ),
        migrations.AddConstraint(
            model_name="taskstate",
            constraint=models.UniqueConstraint(
                fields=("task_type", "exchange", "api_symbol"),
                name="quant_tick_task_state_unique",
            ),
        ),
        migrations.AlterModelOptions(
            name="taskstate",
            options={
                "ordering": ("task_type", "exchange", "api_symbol"),
                "verbose_name": "task state",
                "verbose_name_plural": "task states",
            },
        ),
        migrations.CreateModel(
            name="WebSocketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=EXCHANGE_CHOICES,
                        max_length=255,
                        verbose_name="exchange",
                    ),
                ),
                (
                    "api_symbol",
                    models.CharField(max_length=255, verbose_name="API symbol"),
                ),
                (
                    "significant_trade_filter",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="significant trade filter",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                ("raw_trades", json_field("raw trades", list)),
                ("aggregated_trades", json_field("aggregated trades", list)),
                ("filtered_trades", json_field("filtered trades", list)),
            ],
            options={
                "verbose_name": "websocket data",
                "verbose_name_plural": "websocket data",
                "db_table": "quant_tick_websocket_data",
                "ordering": ("timestamp", "exchange", "api_symbol"),
            },
        ),
        migrations.AddConstraint(
            model_name="websocketdata",
            constraint=models.UniqueConstraint(
                fields=(
                    "exchange",
                    "api_symbol",
                    "significant_trade_filter",
                    "timestamp",
                ),
                name="quant_tick_websocket_data_unique",
            ),
        ),
    ]
