# Generated by Django 5.2 on 2025-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0002_renkobrick"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RenkoBrick",
        ),
        migrations.AlterField(
            model_name="symbol",
            name="exchange",
            field=models.CharField(
                choices=[
                    ("binance", "Binance"),
                    ("bitfinex", "Bitfinex"),
                    ("bitmex", "BitMEX"),
                    ("coinbase", "Coinbase"),
                ],
                max_length=255,
                verbose_name="exchange",
            ),
        ),
    ]
