# Generated by Codex on 2026-05-05

from django.db import migrations, models


EXCHANGE_CHOICES = [
    ("binance", "Binance"),
    ("binance-futures", "Binance Futures"),
    ("bitfinex", "Bitfinex"),
    ("bitmex", "BitMEX"),
    ("coinbase", "Coinbase"),
    ("hyperliquid", "Hyperliquid"),
]


def delete_coinbase_advanced(apps, schema_editor):
    Symbol = apps.get_model("quant_tick", "Symbol")
    TaskState = apps.get_model("quant_tick", "TaskState")
    Symbol.objects.filter(exchange="coinbase-advanced").delete()
    TaskState.objects.filter(exchange="coinbase-advanced").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0003_market_data"),
    ]

    operations = [
        migrations.RunPython(delete_coinbase_advanced, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="symbol",
            name="exchange",
            field=models.CharField(
                choices=EXCHANGE_CHOICES,
                max_length=255,
                verbose_name="exchange",
            ),
        ),
        migrations.AlterField(
            model_name="taskstate",
            name="exchange",
            field=models.CharField(
                blank=True,
                choices=EXCHANGE_CHOICES,
                default="",
                max_length=255,
                verbose_name="exchange",
            ),
        ),
    ]
