# Generated by Django 5.2.9 on 2025-12-19 06:12

import django.db.models.deletion
import quant_tick.models.base
import quant_tick.models.ml
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quant_tick",
            "0003_signal_delete_position_remove_symbol_save_clustered_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureData",
            fields=[
                (
                    "candle_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="feature_data",
                        serialize=False,
                        to="quant_tick.candledata",
                        verbose_name="candle data",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        help_text="Computed feature vector (realizedVol, volRatio, etc.)",
                        verbose_name="json data",
                    ),
                ),
                (
                    "schema_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of sorted feature column names for drift detection",
                        max_length=16,
                        verbose_name="schema hash",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "feature data",
                "verbose_name_plural": "feature data",
                "db_table": "quant_tick_feature_data",
                "ordering": ("candle_data__timestamp",),
            },
        ),
        migrations.CreateModel(
            name="MLArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        help_text="upper or lower",
                        max_length=20,
                        verbose_name="model type",
                    ),
                ),
                (
                    "artifact",
                    models.FileField(
                        upload_to=quant_tick.models.ml.upload_artifact_to,
                        verbose_name="artifact",
                    ),
                ),
                (
                    "brier_score",
                    models.FloatField(
                        blank=True,
                        help_text="Cross-validation metric",
                        null=True,
                        verbose_name="brier score",
                    ),
                ),
                (
                    "feature_columns",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=list,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        help_text="Ordered list of feature column names",
                        verbose_name="feature columns",
                    ),
                ),
                (
                    "is_production",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this model is deployed to quant_horizon",
                        verbose_name="is production",
                    ),
                ),
                (
                    "gcs_path",
                    models.CharField(
                        blank=True,
                        help_text="GCS path: gs://bucket/path/model.joblib",
                        max_length=512,
                        verbose_name="gcs path",
                    ),
                ),
                (
                    "sha256",
                    models.CharField(blank=True, max_length=64, verbose_name="sha256"),
                ),
                (
                    "calibrator",
                    models.BinaryField(
                        blank=True,
                        help_text="Deprecated: calibrator is stored in joblib artifact. This field is redundant and not used by inference.",
                        null=True,
                        verbose_name="calibrator",
                    ),
                ),
                (
                    "horizon",
                    models.IntegerField(
                        blank=True,
                        help_text="Horizon in bars, for per-horizon models.",
                        null=True,
                        verbose_name="horizon",
                    ),
                ),
                (
                    "calibration_method",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("isotonic", "Isotonic"),
                            ("platt", "Platt"),
                        ],
                        default="none",
                        help_text="Calibration method.",
                        max_length=20,
                        verbose_name="calibration method",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        help_text="Data including base rates, calibration drift, etc.",
                        verbose_name="json data",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml artifact",
                "verbose_name_plural": "ml artifacts",
                "db_table": "quant_tick_ml_artifact",
            },
        ),
        migrations.CreateModel(
            name="MLConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_name",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="code name"
                    ),
                ),
                (
                    "inference_lookback",
                    models.IntegerField(
                        default=100,
                        help_text="Number of bars to fetch for inference feature computation",
                        verbose_name="inference lookback",
                    ),
                ),
                (
                    "horizon_bars",
                    models.IntegerField(
                        default=180,
                        help_text="Number of bars for touch prediction horizon",
                        verbose_name="horizon bars",
                    ),
                ),
                (
                    "touch_tolerance",
                    models.FloatField(
                        default=0.15,
                        help_text="Max acceptable P(touch) for valid config. Lower = conservative (LP), Higher = aggressive (perp)",
                        verbose_name="touch tolerance",
                    ),
                ),
                (
                    "min_hold_bars",
                    models.IntegerField(
                        default=15,
                        help_text="Minimum bars before position change",
                        verbose_name="min hold bars",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
                (
                    "last_processed_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last processed bar for idempotency",
                        null=True,
                        verbose_name="last processed timestamp",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="active"),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_config",
                        to="quant_tick.candle",
                        verbose_name="candle",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml config",
                "verbose_name_plural": "ml config",
                "db_table": "quant_tick_ml_config",
            },
        ),
        migrations.CreateModel(
            name="MLSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "lower_bound",
                    models.FloatField(
                        help_text="Lower bound as fraction of entry price (e.g., -0.03)",
                        verbose_name="lower bound",
                    ),
                ),
                (
                    "upper_bound",
                    models.FloatField(
                        help_text="Upper bound as fraction of entry price (e.g., 0.05)",
                        verbose_name="upper bound",
                    ),
                ),
                (
                    "borrow_ratio",
                    models.FloatField(
                        help_text="Borrow ratio for DBI (0.5 = balanced)",
                        verbose_name="borrow ratio",
                    ),
                ),
                ("p_touch_lower", models.FloatField(verbose_name="P(touch lower)")),
                ("p_touch_upper", models.FloatField(verbose_name="P(touch upper)")),
                (
                    "json_data",
                    models.JSONField(
                        blank=True,
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml signal",
                "verbose_name_plural": "ml signals",
                "db_table": "quant_tick_ml_signal",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("backtest", "backtest"),
                            ("paper", "paper"),
                            ("live", "live"),
                        ],
                        default="backtest",
                        max_length=20,
                        verbose_name="position type",
                    ),
                ),
                (
                    "lower_bound",
                    models.FloatField(
                        help_text="Lower bound as fraction of entry price (e.g., -0.03)",
                        verbose_name="lower bound",
                    ),
                ),
                (
                    "upper_bound",
                    models.FloatField(
                        help_text="Upper bound as fraction of entry price (e.g., 0.05)",
                        verbose_name="upper bound",
                    ),
                ),
                (
                    "borrow_ratio",
                    models.FloatField(
                        help_text="Asset allocation (0.5 = balanced, >0.5 = bearish, <0.5 = bullish)",
                        verbose_name="borrow ratio",
                    ),
                ),
                (
                    "entry_timestamp",
                    models.DateTimeField(db_index=True, verbose_name="entry timestamp"),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=38, max_digits=76, verbose_name="entry price"
                    ),
                ),
                (
                    "exit_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="exit timestamp"
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=38,
                        max_digits=76,
                        null=True,
                        verbose_name="exit price",
                    ),
                ),
                (
                    "exit_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("touched_lower", "touched lower"),
                            ("touched_upper", "touched upper"),
                            ("rebalanced", "rebalanced"),
                            ("max_duration", "max duration"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="exit reason",
                    ),
                ),
                (
                    "bars_held",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of bars position was held",
                        null=True,
                        verbose_name="bars held",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("open", "open"),
                            ("closed", "closed"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        blank=True,
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        help_text="Additional data: p_touch_lower, p_touch_upper, width, asymmetry",
                        null=True,
                        verbose_name="json data",
                    ),
                ),
            ],
            options={
                "verbose_name": "position",
                "verbose_name_plural": "positions",
                "db_table": "quant_tick_position",
                "ordering": ["-entry_timestamp"],
            },
        ),
        migrations.RemoveField(
            model_name="signal",
            name="close_candle_data",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="open_candle_data",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="candle",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="strategydata",
            name="strategy",
        ),
        migrations.DeleteModel(
            name="ImbalanceCandle",
        ),
        migrations.DeleteModel(
            name="MACrossoverStrategy",
        ),
        migrations.DeleteModel(
            name="RunCandle",
        ),
        migrations.AlterField(
            model_name="symbol",
            name="exchange",
            field=models.CharField(
                choices=[
                    ("binance", "Binance"),
                    ("bitfinex", "Bitfinex"),
                    ("bitmex", "BitMEX"),
                    ("coinbase", "Coinbase"),
                    ("drift", "Drift"),
                    ("hyperliquid", "Hyperliquid"),
                ],
                max_length=255,
                verbose_name="exchange",
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="symbol_type",
            field=models.CharField(
                choices=[("spot", "spot"), ("perp", "perp")],
                max_length=255,
                verbose_name="type",
            ),
        ),
        migrations.AddField(
            model_name="mlconfig",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ml_config",
                to="quant_tick.symbol",
                verbose_name="symbol",
            ),
        ),
        migrations.AddField(
            model_name="mlartifact",
            name="ml_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ml_artifacts",
                to="quant_tick.mlconfig",
                verbose_name="ml config",
            ),
        ),
        migrations.AddField(
            model_name="mlsignal",
            name="ml_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ml_signals",
                to="quant_tick.mlconfig",
                verbose_name="ml config",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="ml_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="quant_tick.mlconfig",
                verbose_name="ml config",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="ml_signal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="quant_tick.mlsignal",
                verbose_name="ml signal",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="quant_tick.symbol",
                verbose_name="symbol",
            ),
        ),
        migrations.DeleteModel(
            name="Signal",
        ),
        migrations.DeleteModel(
            name="Strategy",
        ),
        migrations.DeleteModel(
            name="StrategyData",
        ),
        migrations.AddConstraint(
            model_name="mlartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_production", True)),
                fields=("ml_config",),
                name="unique_production_model_per_config",
            ),
        ),
        migrations.AddIndex(
            model_name="mlsignal",
            index=models.Index(
                fields=["ml_config", "timestamp"], name="quant_tick__ml_conf_a14ed1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["ml_config", "position_type"],
                name="quant_tick__ml_conf_741d47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["position_type", "status"],
                name="quant_tick__positio_362a47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["entry_timestamp"], name="quant_tick__entry_t_926fe9_idx"
            ),
        ),
    ]
