# Generated by Django 4.1.5 on 2023-01-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quant_tick", "0003_alter_tradedatasummary_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="currency_divisor",
            field=models.PositiveIntegerField(
                default=1, verbose_name="currency divisor"
            ),
        ),
    ]
