# Generated by Django 5.2.5 on 2025-10-11 04:10

import django.db.models.deletion
import quant_tick.models.base
import quant_tick.models.ml
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quant_tick",
            "0003_signal_delete_position_remove_symbol_save_clustered_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MLConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_name",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="code name"
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        help_text="symbols, time_window, features, labeling, cv, model_hparams, thresholds",
                        verbose_name="config json",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=50, verbose_name="status"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_configs",
                        to="quant_tick.candle",
                        verbose_name="candle",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml config",
                "verbose_name_plural": "ml configs",
                "db_table": "quant_tick_ml_config",
            },
        ),
        migrations.CreateModel(
            name="MLFeatureData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_from", models.DateTimeField(verbose_name="timestamp from")),
                ("timestamp_to", models.DateTimeField(verbose_name="timestamp to")),
                (
                    "data",
                    models.FileField(
                        upload_to=quant_tick.models.ml.upload_feature_data_to,
                        verbose_name="data",
                    ),
                ),
                (
                    "schema_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="schema hash"
                    ),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_feature_data",
                        to="quant_tick.candle",
                        verbose_name="candle",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml feature data",
                "verbose_name_plural": "ml feature data",
                "db_table": "quant_tick_ml_feature_data",
                "ordering": ["-timestamp_to"],
            },
        ),
        migrations.CreateModel(
            name="MLRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_from", models.DateTimeField(verbose_name="timestamp from")),
                ("timestamp_to", models.DateTimeField(verbose_name="timestamp to")),
                (
                    "metrics_json",
                    models.JSONField(
                        blank=True,
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="metrics json",
                    ),
                ),
                (
                    "feature_importances_json",
                    models.JSONField(
                        blank=True,
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="feature importances json",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=50, verbose_name="status"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "ml_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_runs",
                        to="quant_tick.mlconfig",
                        verbose_name="ml config",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml run",
                "verbose_name_plural": "ml runs",
                "db_table": "quant_tick_ml_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MLArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact",
                    models.FileField(
                        upload_to=quant_tick.models.ml.upload_artifact_to,
                        verbose_name="artifact",
                    ),
                ),
                ("version", models.CharField(max_length=100, verbose_name="version")),
                (
                    "sha256",
                    models.CharField(blank=True, max_length=64, verbose_name="sha256"),
                ),
                (
                    "ml_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_artifacts",
                        to="quant_tick.mlrun",
                        verbose_name="ml run",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml artifact",
                "verbose_name_plural": "ml artifacts",
                "db_table": "quant_tick_ml_artifact",
            },
        ),
        migrations.CreateModel(
            name="MLSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "probability",
                    models.DecimalField(
                        decimal_places=38, max_digits=76, verbose_name="probability"
                    ),
                ),
                ("side", models.SmallIntegerField(verbose_name="side")),
                (
                    "meta_label",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="meta label"
                    ),
                ),
                (
                    "position_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=38,
                        max_digits=76,
                        null=True,
                        verbose_name="position size",
                    ),
                ),
                (
                    "notes_json",
                    models.JSONField(
                        blank=True,
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="notes json",
                    ),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_signals",
                        to="quant_tick.candle",
                        verbose_name="candle",
                    ),
                ),
                (
                    "ml_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_signals",
                        to="quant_tick.mlartifact",
                        verbose_name="ml artifact",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml signal",
                "verbose_name_plural": "ml signals",
                "db_table": "quant_tick_ml_signal",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["candle", "timestamp"],
                        name="quant_tick__candle__ac6273_idx",
                    )
                ],
            },
        ),
    ]
