# Generated by Django 6.0.3 on 2026-05-25 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quant_tick", "0003_task_state_api_symbol"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candledata",
            options={
                "ordering": ("timestamp", "id"),
                "verbose_name": "candle data",
                "verbose_name_plural": "candle data",
            },
        ),
    ]
