# Generated by Django 5.2.5 on 2025-08-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0003_signal_delete_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="symbol",
            name="save_clustered",
        ),
        migrations.RemoveField(
            model_name="tradedata",
            name="clustered_data",
        ),
        migrations.AlterField(
            model_name="symbol",
            name="save_filtered",
            field=models.BooleanField(
                default=True,
                help_text="Save filtered data?",
                verbose_name="save filtered",
            ),
        ),
    ]
