# Generated by Django 5.2.5 on 2025-10-13 10:42

import django.db.models.deletion
import quant_tick.models.base
import quant_tick.models.ml
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quant_tick",
            "0003_signal_delete_position_remove_symbol_save_clustered_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MLArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact",
                    models.FileField(
                        upload_to=quant_tick.models.ml.upload_artifact_to,
                        verbose_name="artifact",
                    ),
                ),
                ("version", models.CharField(max_length=100, verbose_name="version")),
                (
                    "sha256",
                    models.CharField(blank=True, max_length=64, verbose_name="sha256"),
                ),
            ],
            options={
                "verbose_name": "ml artifact",
                "verbose_name_plural": "ml artifacts",
                "db_table": "quant_tick_ml_artifact",
            },
        ),
        migrations.CreateModel(
            name="MLConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_name",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="code name"
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        help_text="symbols, time_window, features, labeling, cv, model_hparams, thresholds",
                        verbose_name="json data",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=50, verbose_name="status"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_configs",
                        to="quant_tick.candle",
                        verbose_name="candle",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target symbol for trade execution",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_configs",
                        to="quant_tick.symbol",
                        verbose_name="symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml config",
                "verbose_name_plural": "ml config",
                "db_table": "quant_tick_ml_config",
            },
        ),
        migrations.CreateModel(
            name="MLFeatureData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_from", models.DateTimeField(verbose_name="timestamp from")),
                ("timestamp_to", models.DateTimeField(verbose_name="timestamp to")),
                (
                    "file_data",
                    models.FileField(
                        blank=True,
                        upload_to=quant_tick.models.ml.upload_feature_data_to,
                        verbose_name="file data",
                    ),
                ),
                (
                    "schema_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="schema hash"
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="schema version"
                    ),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_feature_data",
                        to="quant_tick.candle",
                        verbose_name="candle",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml feature data",
                "verbose_name_plural": "ml feature data",
                "db_table": "quant_tick_ml_feature_data",
                "ordering": ["-timestamp_to"],
            },
        ),
        migrations.CreateModel(
            name="MLRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_from", models.DateTimeField(verbose_name="timestamp from")),
                ("timestamp_to", models.DateTimeField(verbose_name="timestamp to")),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="metrics",
                    ),
                ),
                (
                    "feature_importances",
                    models.JSONField(
                        blank=True,
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="feature importances",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="metadata",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=50, verbose_name="status"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "ml_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_runs",
                        to="quant_tick.mlconfig",
                        verbose_name="ml config",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml run",
                "verbose_name_plural": "ml runs",
                "db_table": "quant_tick_ml_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MLSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "probability",
                    models.DecimalField(
                        decimal_places=38, max_digits=76, verbose_name="probability"
                    ),
                ),
                ("side", models.SmallIntegerField(verbose_name="side")),
                (
                    "meta_label",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="meta label"
                    ),
                ),
                (
                    "size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=38,
                        max_digits=76,
                        null=True,
                        verbose_name="size",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        blank=True,
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_signals",
                        to="quant_tick.candle",
                        verbose_name="candle",
                    ),
                ),
            ],
            options={
                "verbose_name": "ml signal",
                "verbose_name_plural": "ml signals",
                "db_table": "quant_tick_ml_signal",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("backtest", "backtest"),
                            ("paper", "paper"),
                            ("live", "live"),
                        ],
                        default="backtest",
                        max_length=20,
                        verbose_name="position type",
                    ),
                ),
                (
                    "entry_timestamp",
                    models.DateTimeField(db_index=True, verbose_name="entry timestamp"),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=38, max_digits=76, verbose_name="entry price"
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=38,
                        max_digits=76,
                        null=True,
                        verbose_name="take profit",
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=38,
                        max_digits=76,
                        null=True,
                        verbose_name="stop loss",
                    ),
                ),
                (
                    "max_duration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="max duration"
                    ),
                ),
                (
                    "exit_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="exit timestamp"
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=38,
                        max_digits=76,
                        null=True,
                        verbose_name="exit price",
                    ),
                ),
                (
                    "exit_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("take_profit", "take profit"),
                            ("stop_loss", "stop loss"),
                            ("max_duration", "max duration"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="exit reason",
                    ),
                ),
                ("side", models.SmallIntegerField(verbose_name="side")),
                (
                    "size",
                    models.DecimalField(
                        decimal_places=38, max_digits=76, verbose_name="size"
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=38,
                        max_digits=76,
                        null=True,
                        verbose_name="fees",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("open", "open"),
                            ("closed", "closed"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        blank=True,
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "ml_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="quant_tick.mlrun",
                        verbose_name="ml run",
                    ),
                ),
            ],
            options={
                "verbose_name": "position",
                "verbose_name_plural": "positions",
                "db_table": "quant_tick_position",
                "ordering": ["-entry_timestamp"],
            },
        ),
        migrations.RemoveField(
            model_name="signal",
            name="close_candle_data",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="open_candle_data",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="candle",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="strategydata",
            name="strategy",
        ),
        migrations.DeleteModel(
            name="MACrossoverStrategy",
        ),
        migrations.AddField(
            model_name="mlartifact",
            name="ml_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ml_artifacts",
                to="quant_tick.mlrun",
                verbose_name="ml run",
            ),
        ),
        migrations.AddField(
            model_name="mlsignal",
            name="ml_artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ml_signals",
                to="quant_tick.mlartifact",
                verbose_name="ml artifact",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="ml_signal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="quant_tick.mlsignal",
                verbose_name="ml signal",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="quant_tick.symbol",
                verbose_name="symbol",
            ),
        ),
        migrations.DeleteModel(
            name="Signal",
        ),
        migrations.DeleteModel(
            name="Strategy",
        ),
        migrations.DeleteModel(
            name="StrategyData",
        ),
        migrations.AddIndex(
            model_name="mlsignal",
            index=models.Index(
                fields=["candle", "timestamp"], name="quant_tick__candle__ac6273_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["ml_run", "position_type"],
                name="quant_tick__ml_run__f999c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["position_type", "status"],
                name="quant_tick__positio_362a47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["entry_timestamp"], name="quant_tick__entry_t_926fe9_idx"
            ),
        ),
    ]
