# Generated by Django 5.2.8 on 2025-11-24 13:39

import django.db.models.deletion
from django.db import migrations, models

import quant_tick.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('quant_tick', '0004_mlartifact_mlconfig_mlfeaturedata_mlrun_mlsignal_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mlsignal',
            name='quant_tick__candle__ac6273_idx',
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='quant_tick__ml_run__f999c5_idx',
        ),
        migrations.RemoveField(
            model_name='trendscan',
            name='ml_config',
        ),
        migrations.RemoveField(
            model_name='mlartifact',
            name='ml_run',
        ),
        migrations.RemoveField(
            model_name='position',
            name='ml_run',
        ),
        migrations.RemoveField(
            model_name='trendalert',
            name='ml_config',
        ),
        migrations.DeleteModel(
            name='ImbalanceCandle',
        ),
        migrations.DeleteModel(
            name='RunCandle',
        ),
        migrations.RemoveField(
            model_name='mlartifact',
            name='artifact_type',
        ),
        migrations.RemoveField(
            model_name='mlartifact',
            name='version',
        ),
        migrations.RemoveField(
            model_name='mlconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mlconfig',
            name='last_candle_data',
        ),
        migrations.RemoveField(
            model_name='mlfeaturedata',
            name='schema_version',
        ),
        migrations.RemoveField(
            model_name='mlsignal',
            name='candle',
        ),
        migrations.RemoveField(
            model_name='mlsignal',
            name='meta_label',
        ),
        migrations.RemoveField(
            model_name='mlsignal',
            name='meta_prob',
        ),
        migrations.RemoveField(
            model_name='mlsignal',
            name='ml_artifact',
        ),
        migrations.RemoveField(
            model_name='mlsignal',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='mlsignal',
            name='side',
        ),
        migrations.RemoveField(
            model_name='mlsignal',
            name='size',
        ),
        migrations.RemoveField(
            model_name='position',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='position',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='position',
            name='max_duration',
        ),
        migrations.RemoveField(
            model_name='position',
            name='side',
        ),
        migrations.RemoveField(
            model_name='position',
            name='size',
        ),
        migrations.RemoveField(
            model_name='position',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='position',
            name='take_profit',
        ),
        migrations.RemoveField(
            model_name='position',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mlartifact',
            name='brier_score',
            field=models.FloatField(blank=True, help_text='Cross-validation metric', null=True, verbose_name='brier score'),
        ),
        migrations.AddField(
            model_name='mlartifact',
            name='feature_columns',
            field=models.JSONField(decoder=quant_tick.models.base.QuantTickDecoder, default=list, encoder=quant_tick.models.base.QuantTickEncoder, help_text='Ordered list of feature column names', verbose_name='feature columns'),
        ),
        migrations.AddField(
            model_name='mlartifact',
            name='ml_config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ml_artifacts', to='quant_tick.mlconfig', verbose_name='ml config'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlartifact',
            name='model_type',
            field=models.CharField(default=None, help_text='upper or lower', max_length=20, verbose_name='model type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlconfig',
            name='horizon_bars',
            field=models.IntegerField(default=60, help_text='Number of bars for touch prediction horizon', verbose_name='horizon bars'),
        ),
        migrations.AddField(
            model_name='mlconfig',
            name='last_processed_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last processed bar for idempotency', null=True, verbose_name='last processed timestamp'),
        ),
        migrations.AddField(
            model_name='mlconfig',
            name='lookback_bars',
            field=models.IntegerField(default=100, help_text='Number of bars for feature lookback window', verbose_name='lookback bars'),
        ),
        migrations.AddField(
            model_name='mlconfig',
            name='min_hold_bars',
            field=models.IntegerField(default=15, help_text='Minimum bars before position change', verbose_name='min hold bars'),
        ),
        migrations.AddField(
            model_name='mlconfig',
            name='touch_tolerance',
            field=models.FloatField(default=0.15, help_text='Max acceptable P(touch) for valid config', verbose_name='touch tolerance'),
        ),
        migrations.AddField(
            model_name='mlsignal',
            name='borrow_ratio',
            field=models.FloatField(default=None, help_text='Borrow ratio for DBI (0.5 = balanced)', verbose_name='borrow ratio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlsignal',
            name='lower_bound',
            field=models.FloatField(default=None, help_text='Lower bound as fraction of entry price (e.g., -0.03)', verbose_name='lower bound'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlsignal',
            name='ml_config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ml_signals', to='quant_tick.mlconfig', verbose_name='ml config'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlsignal',
            name='p_touch_lower',
            field=models.FloatField(default=None, verbose_name='P(touch lower)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlsignal',
            name='p_touch_upper',
            field=models.FloatField(default=None, verbose_name='P(touch upper)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlsignal',
            name='upper_bound',
            field=models.FloatField(default=None, help_text='Upper bound as fraction of entry price (e.g., 0.05)', verbose_name='upper bound'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='bars_held',
            field=models.IntegerField(blank=True, help_text='Number of bars position was held', null=True, verbose_name='bars held'),
        ),
        migrations.AddField(
            model_name='position',
            name='borrow_ratio',
            field=models.FloatField(default=None, help_text='Asset allocation (0.5 = balanced, >0.5 = bearish, <0.5 = bullish)', verbose_name='borrow ratio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='lower_bound',
            field=models.FloatField(default=None, help_text='Lower bound as fraction of entry price (e.g., -0.03)', verbose_name='lower bound'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='ml_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='quant_tick.mlconfig', verbose_name='ml config'),
        ),
        migrations.AddField(
            model_name='position',
            name='upper_bound',
            field=models.FloatField(default=None, help_text='Upper bound as fraction of entry price (e.g., 0.05)', verbose_name='upper bound'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mlconfig',
            name='candle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_config', to='quant_tick.candle', verbose_name='candle'),
        ),
        migrations.AlterField(
            model_name='mlconfig',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='mlconfig',
            name='json_data',
            field=models.JSONField(decoder=quant_tick.models.base.QuantTickDecoder, default=dict, encoder=quant_tick.models.base.QuantTickEncoder, verbose_name='json data'),
        ),
        migrations.AlterField(
            model_name='mlconfig',
            name='symbol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ml_config', to='quant_tick.symbol', verbose_name='symbol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='exit_reason',
            field=models.CharField(blank=True, choices=[('touched_lower', 'touched lower'), ('touched_upper', 'touched upper'), ('rebalanced', 'rebalanced'), ('max_duration', 'max duration')], max_length=50, null=True, verbose_name='exit reason'),
        ),
        migrations.AlterField(
            model_name='position',
            name='json_data',
            field=models.JSONField(blank=True, decoder=quant_tick.models.base.QuantTickDecoder, encoder=quant_tick.models.base.QuantTickEncoder, help_text='Additional data: p_touch_lower, p_touch_upper, width, asymmetry', null=True, verbose_name='json data'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbol_type',
            field=models.CharField(choices=[('spot', 'spot'), ('perp', 'perp')], max_length=255, verbose_name='type'),
        ),
        migrations.AddIndex(
            model_name='mlsignal',
            index=models.Index(fields=['ml_config', 'timestamp'], name='quant_tick__ml_conf_a14ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['ml_config', 'position_type'], name='quant_tick__ml_conf_741d47_idx'),
        ),
        migrations.DeleteModel(
            name='TrendAlert',
        ),
        migrations.DeleteModel(
            name='TrendScan',
        ),
        migrations.DeleteModel(
            name='MLRun',
        ),
        migrations.RemoveField(
            model_name='mlconfig',
            name='lookback_bars',
        ),
        migrations.AddField(
            model_name='mlconfig',
            name='inference_lookback',
            field=models.IntegerField(default=100, help_text='Number of bars to fetch for inference', verbose_name='inference lookback'),
        ),
    ]
