# Generated by Django 5.2.5 on 2025-08-25 09:41

from django.db import migrations, models


def fake(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0004_remove_symbol_save_clustered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="save_clustered",
            field=models.BooleanField(
                default=True,
                help_text="Save clustered data?",
                verbose_name="save clustered",
            ),
        ),
        migrations.AddField(
            model_name="tradedata",
            name="clustered_data",
            field=models.FileField(
                blank=True,
                upload_to=fake,
                verbose_name="clustered data",
            ),
        ),
    ]
