# Generated by Django 6.0.3 on 2026-06-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_tick', '0004_alter_candledata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstate',
            name='exchange',
            field=models.CharField(choices=[('all', 'All'), ('binance', 'Binance'), ('binance-futures', 'Binance Futures'), ('bitfinex', 'Bitfinex'), ('bitmex', 'BitMEX'), ('coinbase', 'Coinbase'), ('hyperliquid', 'Hyperliquid')], max_length=255, verbose_name='exchange'),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='task_type',
            field=models.CharField(choices=[('aggregate_trades', 'Aggregate trades'), ('aggregate_candles', 'Aggregate candles'), ('fetch_exchange_data', 'Fetch exchange data'), ('compact', 'Compact')], max_length=255, verbose_name='task type'),
        ),
    ]
