# Generated by Django 5.2.9 on 2025-12-31 05:01

import django.db.models.deletion
from django.db import migrations, models

import quant_tick.models.base


def fake(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "quant_tick",
            "0001_initial_squashed_0005_remove_signal_close_candle_data_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=10, max_digits=20, verbose_name="rate"
                    ),
                ),
            ],
            options={
                "verbose_name": "funding rate",
                "verbose_name_plural": "funding rates",
                "db_table": "quant_tick_funding_rate",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RenkoData",
            fields=[
                (
                    "candle_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="renko_data",
                        serialize=False,
                        to="quant_tick.candledata",
                        verbose_name="candle data",
                    ),
                ),
                ("level", models.IntegerField(db_index=True, verbose_name="level")),
                (
                    "sequence",
                    models.BigIntegerField(db_index=True, verbose_name="sequence"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("body", "Body"), ("wick", "Wick")],
                        max_length=4,
                        verbose_name="kind",
                    ),
                ),
                (
                    "direction",
                    models.SmallIntegerField(
                        choices=[(-1, "Down"), (1, "Up")], verbose_name="direction"
                    ),
                ),
            ],
            options={
                "verbose_name": "renko data",
                "verbose_name_plural": "renko data",
                "db_table": "quant_tick_renko_data",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "probability",
                    models.FloatField(
                        blank=True, null=True, verbose_name="probability"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("take", "Take"),
                            ("skip", "Skip"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="decision",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        default=dict,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        verbose_name="json data",
                    ),
                ),
            ],
            options={
                "verbose_name": "signal",
                "verbose_name_plural": "signals",
                "db_table": "quant_tick_signal",
            },
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_name",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="code name"
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_tick.models.base.QuantTickDecoder,
                        encoder=quant_tick.models.base.QuantTickEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "last_processed_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last processed timestamp for idempotency",
                        null=True,
                        verbose_name="last processed timestamp",
                    ),
                ),
            ],
            options={
                "verbose_name": "strategy",
                "verbose_name_plural": "strategies",
                "db_table": "quant_tick_strategy",
            },
        ),
        migrations.RemoveField(
            model_name="featuredata",
            name="candle_data",
        ),
        migrations.RemoveField(
            model_name="mlconfig",
            name="candle",
        ),
        migrations.RemoveField(
            model_name="mlconfig",
            name="symbol",
        ),
        migrations.RemoveConstraint(
            model_name="mlartifact",
            name="unique_production_model_per_config",
        ),
        migrations.RemoveIndex(
            model_name="mlsignal",
            name="quant_tick__ml_conf_a14ed1_idx",
        ),
        migrations.RemoveIndex(
            model_name="position",
            name="quant_tick__ml_conf_741d47_idx",
        ),
        migrations.RemoveIndex(
            model_name="position",
            name="quant_tick__positio_362a47_idx",
        ),
        migrations.RemoveIndex(
            model_name="position",
            name="quant_tick__entry_t_926fe9_idx",
        ),
        migrations.RemoveField(
            model_name="mlartifact",
            name="ml_config",
        ),
        migrations.RemoveField(
            model_name="mlsignal",
            name="ml_config",
        ),
        migrations.RemoveField(
            model_name="position",
            name="ml_config",
        ),
        migrations.RemoveField(
            model_name="position",
            name="ml_signal",
        ),
        migrations.CreateModel(
            name="RenkoBrick",
            fields=[],
            options={
                "verbose_name": "renko brick",
                "verbose_name_plural": "renko bricks",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.constantcandle",),
        ),
        migrations.AlterModelOptions(
            name="mlartifact",
            options={
                "verbose_name": "meta artifact",
                "verbose_name_plural": "meta artifacts",
            },
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": "position", "verbose_name_plural": "positions"},
        ),
        migrations.RemoveField(
            model_name="mlartifact",
            name="artifact",
        ),
        migrations.RemoveField(
            model_name="mlartifact",
            name="brier_score",
        ),
        migrations.RemoveField(
            model_name="mlartifact",
            name="calibration_method",
        ),
        migrations.RemoveField(
            model_name="mlartifact",
            name="calibrator",
        ),
        migrations.RemoveField(
            model_name="mlartifact",
            name="feature_columns",
        ),
        migrations.RemoveField(
            model_name="mlartifact",
            name="gcs_path",
        ),
        migrations.RemoveField(
            model_name="mlartifact",
            name="horizon",
        ),
        migrations.RemoveField(
            model_name="mlartifact",
            name="is_production",
        ),
        migrations.RemoveField(
            model_name="mlartifact",
            name="model_type",
        ),
        migrations.RemoveField(
            model_name="mlartifact",
            name="sha256",
        ),
        migrations.RemoveField(
            model_name="position",
            name="bars_held",
        ),
        migrations.RemoveField(
            model_name="position",
            name="borrow_ratio",
        ),
        migrations.RemoveField(
            model_name="position",
            name="entry_price",
        ),
        migrations.RemoveField(
            model_name="position",
            name="entry_timestamp",
        ),
        migrations.RemoveField(
            model_name="position",
            name="exit_price",
        ),
        migrations.RemoveField(
            model_name="position",
            name="exit_reason",
        ),
        migrations.RemoveField(
            model_name="position",
            name="exit_timestamp",
        ),
        migrations.RemoveField(
            model_name="position",
            name="lower_bound",
        ),
        migrations.RemoveField(
            model_name="position",
            name="position_type",
        ),
        migrations.RemoveField(
            model_name="position",
            name="status",
        ),
        migrations.RemoveField(
            model_name="position",
            name="symbol",
        ),
        migrations.RemoveField(
            model_name="position",
            name="upper_bound",
        ),
        migrations.AddField(
            model_name="mlartifact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=None, verbose_name="created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mlartifact",
            name="feature_cols",
            field=models.JSONField(
                decoder=quant_tick.models.base.QuantTickDecoder,
                default=list,
                encoder=quant_tick.models.base.QuantTickEncoder,
                help_text="Feature columns expected by the model.",
                verbose_name="feature columns",
            ),
        ),
        migrations.AddField(
            model_name="mlartifact",
            name="file_data",
            field=models.FileField(
                default=None,
                upload_to=fake,
                verbose_name="bundle file",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mlartifact",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AddField(
            model_name="mlartifact",
            name="model_kind",
            field=models.CharField(
                default=None,
                help_text="Identifier for bundle format, e.g., meta_logreg.",
                max_length=64,
                verbose_name="model kind",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mlartifact",
            name="next_retrain_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the strategy should be retrained again.",
                null=True,
                verbose_name="next retrain at",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="close_candle_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="close_positions",
                to="quant_tick.candledata",
                verbose_name="candle data",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="open_candle_data",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="open_positions",
                to="quant_tick.candledata",
                verbose_name="candle data",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mlartifact",
            name="json_data",
            field=models.JSONField(
                decoder=quant_tick.models.base.QuantTickDecoder,
                default=dict,
                encoder=quant_tick.models.base.QuantTickEncoder,
                verbose_name="json data",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="json_data",
            field=models.JSONField(
                decoder=quant_tick.models.base.QuantTickDecoder,
                encoder=quant_tick.models.base.QuantTickEncoder,
                null=True,
                verbose_name="json data",
            ),
        ),
        migrations.AlterModelTable(
            name="mlartifact",
            table="quant_tick_meta_artifact",
        ),
        migrations.AddField(
            model_name="fundingrate",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_rates",
                to="quant_tick.symbol",
                verbose_name="symbol",
            ),
        ),
        migrations.AddIndex(
            model_name="renkodata",
            index=models.Index(
                fields=["level", "sequence"], name="quant_tick__level_2fa5a4_idx"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="signal",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="position",
                to="quant_tick.signal",
                verbose_name="signal",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="candle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quant_tick.candle",
                verbose_name="candle",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="symbol",
            field=models.ForeignKey(
                help_text="Target symbol for multi-exchange feature selection and trading.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategies",
                to="quant_tick.symbol",
                verbose_name="symbol",
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="strategy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signals",
                to="quant_tick.strategy",
                verbose_name="strategy",
            ),
        ),
        migrations.AddField(
            model_name="mlartifact",
            name="strategy",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="quant_tick.strategy",
                verbose_name="strategy",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="position",
            name="strategy",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="quant_tick.strategy",
                verbose_name="strategy",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="FeatureData",
        ),
        migrations.DeleteModel(
            name="MLConfig",
        ),
        migrations.DeleteModel(
            name="MLSignal",
        ),
        migrations.AddIndex(
            model_name="fundingrate",
            index=models.Index(
                fields=["symbol", "timestamp"], name="quant_tick__symbol__08a316_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fundingrate",
            unique_together={("symbol", "timestamp")},
        ),
        migrations.AlterField(
            model_name="signal",
            name="decision",
            field=models.CharField(
                choices=[("take", "Take"), ("pass", "Pass")],
                max_length=16,
                verbose_name="decision",
            ),
        ),
        migrations.CreateModel(
            name="MACrossoverStrategy",
            fields=[],
            options={
                "verbose_name": "ma crossover strategy",
                "verbose_name_plural": "ma crossover strategies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.strategy",),
        ),
        migrations.CreateModel(
            name="Renko2BrickReversalStrategy",
            fields=[],
            options={
                "verbose_name": "renko 2-brick reversal strategy",
                "verbose_name_plural": "renko 2-brick reversal strategies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.strategy",),
        ),
        migrations.AlterField(
            model_name="signal",
            name="decision",
            field=models.CharField(
                choices=[("take", "take"), ("pass", "pass")],
                db_index=True,
                max_length=16,
                verbose_name="decision",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="last_candle_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                to="quant_tick.candledata",
                verbose_name="last candle data",
            ),
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="last_processed_timestamp",
        ),
        migrations.AlterField(
            model_name="strategy",
            name="symbol",
            field=models.ForeignKey(
                help_text="Target symbol for feature selection and trading.",
                on_delete=models.deletion.CASCADE,
                related_name="strategies",
                to="quant_tick.symbol",
                verbose_name="symbol",
            ),
        ),
        migrations.AlterField(
            model_name="renkodata",
            name="direction",
            field=models.SmallIntegerField(
                choices=[(1, "long"), (-1, "short")], verbose_name="direction"
            ),
        ),
        migrations.AlterField(
            model_name="renkodata",
            name="kind",
            field=models.CharField(
                choices=[("body", "body"), ("wick", "wick")],
                max_length=4,
                verbose_name="kind",
            ),
        ),
    ]
