# Generated by Django 5.2.8 on 2025-11-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_tick', '0005_remove_mlrun_ml_config_remove_trendscan_ml_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlconfig',
            name='horizon_bars',
            field=models.IntegerField(default=180, help_text='Number of bars for touch prediction horizon', verbose_name='horizon bars'),
        ),
        migrations.AlterField(
            model_name='mlconfig',
            name='inference_lookback',
            field=models.IntegerField(default=100, help_text='Number of bars to fetch for inference feature computation', verbose_name='inference lookback'),
        ),
    ]
