# Generated by Django 5.2.5 on 2025-08-28 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0005_symbol_save_clustered_tradedata_clustered_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="symbol",
            name="save_clustered",
        ),
        migrations.RemoveField(
            model_name="tradedata",
            name="clustered_data",
        ),
    ]
