# Generated by Django 6.0.3 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0005_alter_taskstate_exchange_alter_taskstate_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskstate",
            name="lock_token",
            field=models.UUIDField(
                blank=True,
                null=True,
                verbose_name="lock token",
            ),
        ),
    ]
