# Generated by Django 4.1.7 on 2023-03-03 00:33

from django.db import migrations, models
import quant_tick.models.base


class Migration(migrations.Migration):
    dependencies = [
        ("quant_tick", "0005_symbol_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candlecache",
            name="json_data",
            field=models.JSONField(
                decoder=quant_tick.models.base.QuantTickDecoder,
                default=dict,
                encoder=quant_tick.models.base.QuantTickEncoder,
                verbose_name="json data",
            ),
        ),
    ]
