# Generated by Django 6.0.3 on 2026-07-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_tick', '0006_taskstate_lock_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('binance-futures', 'Binance Futures'), ('bitfinex', 'Bitfinex'), ('bitmex', 'BitMEX'), ('coinbase', 'Coinbase'), ('deribit', 'Deribit'), ('hyperliquid', 'Hyperliquid')], max_length=255, verbose_name='exchange'),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='exchange',
            field=models.CharField(choices=[('all', 'All'), ('binance', 'Binance'), ('binance-futures', 'Binance Futures'), ('bitfinex', 'Bitfinex'), ('bitmex', 'BitMEX'), ('coinbase', 'Coinbase'), ('deribit', 'Deribit'), ('hyperliquid', 'Hyperliquid')], max_length=255, verbose_name='exchange'),
        ),
        migrations.AlterField(
            model_name='websocketdata',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('binance-futures', 'Binance Futures'), ('bitfinex', 'Bitfinex'), ('bitmex', 'BitMEX'), ('coinbase', 'Coinbase'), ('deribit', 'Deribit'), ('hyperliquid', 'Hyperliquid')], max_length=255, verbose_name='exchange'),
        ),
    ]
