# Generated by Django 5.2.9 on 2026-01-02 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0006_fundingrate_renkodata_signal_strategy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="renkodata",
            name="kind",
        ),
        migrations.AddField(
            model_name="renkodata",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wick_children",
                to="quant_tick.candledata",
                verbose_name="parent",
            ),
        ),
    ]
