# Generated by Django 5.2.8 on 2025-11-28 23:58

import quant_tick.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_tick', '0006_alter_mlconfig_horizon_bars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlartifact',
            name='calibration_method',
            field=models.CharField(choices=[('none', 'None'), ('isotonic', 'Isotonic'), ('platt', 'Platt')], default='none', help_text='Calibration method used for this model', max_length=20, verbose_name='calibration method'),
        ),
        migrations.AddField(
            model_name='mlartifact',
            name='calibrator',
            field=models.BinaryField(blank=True, help_text='Pickled isotonic calibrator for this model', null=True, verbose_name='calibrator'),
        ),
        migrations.AddField(
            model_name='mlartifact',
            name='horizon',
            field=models.IntegerField(blank=True, help_text='Horizon in bars (for per-horizon models)', null=True, verbose_name='horizon'),
        ),
        migrations.AddField(
            model_name='mlartifact',
            name='json_data',
            field=models.JSONField(decoder=quant_tick.models.base.QuantTickDecoder, default=dict, encoder=quant_tick.models.base.QuantTickEncoder, help_text='Metadata including base rates, calibration drift, etc.', verbose_name='json data'),
        ),
        migrations.AlterField(
            model_name='mlconfig',
            name='touch_tolerance',
            field=models.FloatField(default=0.15, help_text='Max acceptable P(touch) for valid config. Lower = conservative (LP), Higher = aggressive (perp)', verbose_name='touch tolerance'),
        ),
    ]
