# Generated by Django 5.2.9 on 2026-01-03 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0007_remove_renkodata_kind_renkodata_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candle",
            name="symbols",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="symbol",
        ),
        migrations.AddField(
            model_name="candle",
            name="symbol",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quant_tick.symbol",
                verbose_name="symbol",
            ),
        ),
    ]
