# Generated by Django 6.1 on 2026-08-13 02:30

import django.db.models.deletion
import quant_tick.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_tick', '0007_alter_symbol_exchange_alter_taskstate_exchange_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerpetualStatsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='timestamp')),
                ('frequency', models.PositiveIntegerField(db_index=True, verbose_name='frequency')),
                ('open_interest', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='open interest')),
                ('open_interest_value', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='open interest value')),
                ('single_open_interest', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='single open interest')),
                ('top_trader_long_short_account_ratio', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='top trader long short account ratio')),
                ('top_trader_long_short_position_ratio', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='top trader long short position ratio')),
                ('long_short_account_ratio', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='long short account ratio')),
                ('taker_long_short_volume_ratio', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='taker long short volume ratio')),
                ('long_account_ratio', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='long account ratio')),
                ('short_account_ratio', models.DecimalField(blank=True, decimal_places=38, max_digits=76, null=True, verbose_name='short account ratio')),
                ('open_interest_unit', models.CharField(blank=True, default='', max_length=32, verbose_name='open interest unit')),
                ('json_data', models.JSONField(decoder=quant_tick.models.base.QuantTickDecoder, default=dict, encoder=quant_tick.models.base.QuantTickEncoder, verbose_name='json data')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perpetual_stats_data', to='quant_tick.symbol')),
            ],
            options={
                'verbose_name': 'perpetual stats data',
                'verbose_name_plural': 'perpetual stats data',
                'db_table': 'quant_tick_perpetual_stats_data',
                'ordering': ('timestamp',),
                'unique_together': {('symbol', 'frequency', 'timestamp')},
            },
        ),
    ]
