# Generated by Django 6.0.3 on 2026-07-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_tick', '0007_alter_symbol_exchange_alter_taskstate_exchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='funding_interval',
            field=models.DurationField(blank=True, editable=False, help_text='Funding cadence discovered from exchange metadata.', null=True, verbose_name='funding interval'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('binance-futures', 'Binance Futures'), ('bitfinex', 'Bitfinex'), ('bitmex', 'BitMEX'), ('bybit', 'Bybit'), ('coinbase', 'Coinbase'), ('deribit', 'Deribit'), ('hyperliquid', 'Hyperliquid')], max_length=255, verbose_name='exchange'),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='exchange',
            field=models.CharField(choices=[('all', 'All'), ('binance', 'Binance'), ('binance-futures', 'Binance Futures'), ('bitfinex', 'Bitfinex'), ('bitmex', 'BitMEX'), ('bybit', 'Bybit'), ('coinbase', 'Coinbase'), ('deribit', 'Deribit'), ('hyperliquid', 'Hyperliquid')], max_length=255, verbose_name='exchange'),
        ),
        migrations.AlterField(
            model_name='websocketdata',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('binance-futures', 'Binance Futures'), ('bitfinex', 'Bitfinex'), ('bitmex', 'BitMEX'), ('bybit', 'Bybit'), ('coinbase', 'Coinbase'), ('deribit', 'Deribit'), ('hyperliquid', 'Hyperliquid')], max_length=255, verbose_name='exchange'),
        ),
    ]
