# Generated by Django 5.2.8 on 2025-12-02 00:08

import quant_tick.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_tick', '0007_mlartifact_calibration_method_mlartifact_calibrator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlartifact',
            name='calibration_method',
            field=models.CharField(choices=[('none', 'None'), ('isotonic', 'Isotonic'), ('platt', 'Platt')], default='none', help_text='Calibration method.', max_length=20, verbose_name='calibration method'),
        ),
        migrations.AlterField(
            model_name='mlartifact',
            name='calibrator',
            field=models.BinaryField(blank=True, help_text='Pickled isotonic calibrator.', null=True, verbose_name='calibrator'),
        ),
        migrations.AlterField(
            model_name='mlartifact',
            name='horizon',
            field=models.IntegerField(blank=True, help_text='Horizon in bars, for per-horizon models.', null=True, verbose_name='horizon'),
        ),
        migrations.AlterField(
            model_name='mlartifact',
            name='json_data',
            field=models.JSONField(decoder=quant_tick.models.base.QuantTickDecoder, default=dict, encoder=quant_tick.models.base.QuantTickEncoder, help_text='Data including base rates, calibration drift, etc.', verbose_name='json data'),
        ),
    ]
