# Generated by Django 5.2.9 on 2026-01-04 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0009_add_renkodata_kind_remove_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candle",
            name="symbol",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="quant_tick.symbol",
                verbose_name="symbol",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tradedata",
            name="frequency",
            field=models.PositiveIntegerField(
                choices=[(1, "Minute"), (60, "Hour"), (1440, "Day")],
                db_index=True,
                verbose_name="frequency",
            ),
        ),
    ]
