# Generated by Django 5.2.10 on 2026-02-02 00:05

import quant_tick.models.candles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0010_alter_candle_symbol_alter_tradedata_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="renkodata",
            name="candle_data",
        ),
        migrations.DeleteModel(
            name="Renko2BrickReversalStrategy",
        ),
        migrations.DeleteModel(
            name="RenkoBrick",
        ),
        migrations.CreateModel(
            name="SignificantCluster",
            fields=[],
            options={
                "verbose_name": "significant cluster",
                "verbose_name_plural": "significant clusters",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(quant_tick.models.candles.CacheResetMixin, "quant_tick.candle"),
        ),
        migrations.CreateModel(
            name="ClusterMomentumStrategy",
            fields=[],
            options={
                "verbose_name": "cluster momentum strategy",
                "verbose_name_plural": "cluster momentum strategies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.strategy",),
        ),
        migrations.AddIndex(
            model_name="candledata",
            index=models.Index(
                fields=["candle", "timestamp"], name="candle_timestamp_idx"
            ),
        ),
        migrations.DeleteModel(
            name="RenkoData",
        ),
        migrations.CreateModel(
            name="AdaptiveSignificantCluster",
            fields=[],
            options={
                "verbose_name": "adaptive significant cluster",
                "verbose_name_plural": "adaptive significant clusters",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quant_tick.significantcluster",),
        ),
    ]
