# Generated by Django 5.2.10 on 2026-02-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quant_tick", "0011_remove_renkodata_candle_data_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fundingrate",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="fundingrate",
            name="symbol",
        ),
        migrations.RemoveField(
            model_name="mlartifact",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="position",
            name="close_candle_data",
        ),
        migrations.RemoveField(
            model_name="position",
            name="open_candle_data",
        ),
        migrations.RemoveField(
            model_name="position",
            name="signal",
        ),
        migrations.RemoveField(
            model_name="position",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="candle",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="last_candle_data",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="polymorphic_ctype",
        ),
        migrations.DeleteModel(
            name="AdaptiveSignificantCluster",
        ),
        migrations.DeleteModel(
            name="ClusterMomentumStrategy",
        ),
        migrations.DeleteModel(
            name="MACrossoverStrategy",
        ),
        migrations.DeleteModel(
            name="SignificantCluster",
        ),
        migrations.RemoveIndex(
            model_name="candledata",
            name="candle_timestamp_idx",
        ),
        migrations.DeleteModel(
            name="FundingRate",
        ),
        migrations.DeleteModel(
            name="MLArtifact",
        ),
        migrations.DeleteModel(
            name="Position",
        ),
        migrations.DeleteModel(
            name="Signal",
        ),
        migrations.DeleteModel(
            name="Strategy",
        ),
    ]
