# Generated by Django 6.0.3 on 2026-04-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quant_tick", "0014_remove_symbol_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="date_from",
            field=models.DateField(null=True, verbose_name="date from"),
        ),
        migrations.AlterField(
            model_name="candlecache",
            name="frequency",
            field=models.PositiveIntegerField(db_index=True, verbose_name="frequency"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="exchange",
            field=models.CharField(
                choices=[
                    ("binance", "Binance"),
                    ("bitfinex", "Bitfinex"),
                    ("bitmex", "BitMEX"),
                    ("coinbase", "Coinbase"),
                ],
                max_length=255,
                verbose_name="exchange",
            ),
        ),
        migrations.AlterField(
            model_name="taskstate",
            name="exchange",
            field=models.CharField(
                blank=True,
                choices=[
                    ("binance", "Binance"),
                    ("bitfinex", "Bitfinex"),
                    ("bitmex", "BitMEX"),
                    ("coinbase", "Coinbase"),
                ],
                default="",
                max_length=255,
                verbose_name="exchange",
            ),
        ),
    ]
