# Generated by Django 4.1.5 on 2023-01-14 08:42

from django.db import migrations, models
import django.db.models.deletion
import quant_candles.models.base
import quant_candles.models.trades


class Migration(migrations.Migration):

    dependencies = [
        ("quant_candles", "0002_candlereadonlydata_timebasedcandle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeDataSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "file_data",
                    models.FileField(
                        blank=True,
                        upload_to=quant_candles.models.trades.upload_trade_data_summary_to,
                        verbose_name="file data",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        decoder=quant_candles.models.base.QuantCandlesDecoder,
                        encoder=quant_candles.models.base.QuantCandlesEncoder,
                        null=True,
                        verbose_name="json data",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_data_summary",
                        to="quant_candles.symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "trade data summary",
                "verbose_name_plural": "trade data summary",
                "db_table": "quant_candles_trade_data_summary",
                "ordering": ("date",),
            },
        ),
    ]
