# Generated by Django 4.1.7 on 2023-02-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quant_candles", "0004_symbol_currency_divisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
