BITFINEX_MAX_REQUESTS_RESET = "BITFINEX_MAX_REQUESTS_RESET"
BITFINEX_TOTAL_REQUESTS = "BITFINEX_TOTAL_REQUESTS"

API_URL = "https://api-pub.bitfinex.com/v2/trades"
MAX_REQUESTS = 90
MAX_REQUESTS_RESET = 60  # 1 minute
MAX_RESULTS = 10000
MIN_ELAPSED_PER_REQUEST = 0
