# Generated by Django 4.0.5 on 2022-08-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quant_werks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candle",
            name="code_name",
            field=models.SlugField(
                max_length=255, unique=True, verbose_name="code name"
            ),
        ),
    ]
