PHOENIX_MAX_REQUESTS_RESET = "PHOENIX_MAX_REQUESTS_RESET"
PHOENIX_TOTAL_REQUESTS = "PHOENIX_TOTAL_REQUESTS"

API_URL = "https://perp-api.phoenix.trade"
MAX_REQUESTS = 1
MAX_REQUESTS_RESET = 1
MIN_ELAPSED_PER_REQUEST = MAX_REQUESTS_RESET / MAX_REQUESTS
TRADE_MAX_RESULTS = 1000
CANDLE_MAX_RESULTS = 2500
FUNDING_MAX_RESULTS = 1000
MARKET_HISTORY_INTERVAL = "1h"
MARKET_HISTORY_MAX_RESULTS = 1000
CANDLE_RESOLUTIONS_BY_MINUTES = {
    1: "1m",
    5: "5m",
    15: "15m",
    30: "30m",
    60: "1h",
    240: "4h",
    1440: "1d",
}
