BITFINEX_MAX_REQUESTS_RESET = "BITFINEX_MAX_REQUESTS_RESET"
BITFINEX_TOTAL_REQUESTS = "BITFINEX_TOTAL_REQUESTS"

API_URL = "https://api-pub.bitfinex.com/v2"
MAX_REQUESTS = 10
MAX_REQUESTS_RESET = 60
TRADE_MAX_RESULTS = 10000
CANDLE_MAX_RESULTS = 10000
FUNDING_MAX_RESULTS = 5000
MIN_ELAPSED_PER_REQUEST = 6  # 10 requests per minute
