# Generated by Django 4.0.5 on 2022-06-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofeed_werks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedtradedata',
            name='stats',
            field=models.JSONField(blank=True, null=True, verbose_name='stats'),
        ),
        migrations.AlterField(
            model_name='aggregatedtradedata',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_trade_data', to='cryptofeed_werks.symbol'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('bitfinex', 'Bitfinex'), ('bitmex', 'BitMEX'), ('bybit', 'Bybit'), ('coinbase', 'Coinbase'), ('ftx', 'FTX')], max_length=255, verbose_name='exchange'),
        ),
    ]
