# Generated by Django 4.0.5 on 2022-08-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofeed_werks', '0003_rename_config_candledata_candle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatedtradedata',
            name='exchange_volume',
        ),
        migrations.RemoveField(
            model_name='aggregatedtradedata',
            name='is_hourly',
        ),
        migrations.RemoveField(
            model_name='aggregatedtradedata',
            name='volume',
        ),
        migrations.AlterField(
            model_name='candlesymbol',
            name='date_from',
            field=models.DateField(null=True, verbose_name='date from'),
        ),
        migrations.AlterField(
            model_name='candlesymbol',
            name='date_to',
            field=models.DateField(null=True, verbose_name='date to'),
        ),
        migrations.AlterUniqueTogether(
            name='candlesymbol',
            unique_together={('candle', 'symbol')},
        ),
    ]
